services:
  - type: web
    name: skinmatch
    rootDir: backend
    env: docker
    plan: free
    autoDeploy: true
    startCommand: gunicorn apidemo.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: skinmatch-m8wc.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://skinmatch-m8wc.onrender.com

  - type: job
    name: migrate-db
    rootDir: backend
    env: docker
    plan: free
    autoDeploy: false
    startCommand: python manage.py migrate
