from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from typing import Iterable

from django.core.management.base import BaseCommand
from django.db import transaction
from django.utils.text import slugify

from quiz.models import (
    Ingredient,
    Product,
    ProductConcern,
    ProductIngredient,
    ProductSkinType,
    RestrictionTag,
    SkinConcern,
    SkinTypeTag,
)


@dataclass
class ProductSeed:
    brand: str
    name: str
    origin: str
    category: str
    price: str
    currency: str
    summary: str
    hero_ingredients: str
    rating: float | None
    concerns: list[str]
    ingredients: list[str]
    skin_types: list[str]
    restrictions: list[str]
    product_url: str | None = None
    image: str | None = None


CONCERNS: tuple[tuple[str, str], ...] = (
    ("acne-breakouts", "Acne & Breakouts"),
    ("blackheads", "Blackheads"),
    ("fine-lines-wrinkles", "Fine Lines & Wrinkles"),
    ("uneven-skin-texture", "Uneven Skin Texture"),
    ("hyperpigmentation", "Hyperpigmentation"),
    ("redness", "Redness"),
    ("damaged-skin-barrier", "Damaged Skin Barrier"),
    ("dull-skin", "Dull Skin"),
    ("dehydrated-skin", "Dehydrated Skin"),
    ("excess-oil", "Excess Oil"),
    ("large-pores", "Large Pores"),
    ("dark-circles", "Dark Circles"),
    ("puffiness", "Puffiness"),
    ("sensitivity", "Sensitivity"),
    ("dryness", "Dryness"),
    ("sun-protection", "Sun Protection"),
    ("firmness", "Firmness & Elasticity"),
    ("blemishes", "Blemishes"),
)

SKIN_TYPES: tuple[tuple[str, str], ...] = (
    ("dry", "Dry"),
    ("oily", "Oily"),
    ("normal", "Normal"),
    ("combination", "Combination"),
    ("sensitive", "Sensitive"),
)

RESTRICTIONS: tuple[tuple[str, str], ...] = (
    ("vegan", "Vegan"),
    ("cruelty-free", "Cruelty-Free"),
    ("fragrance-free", "Fragrance-Free"),
    ("alcohol-free", "Alcohol-Free"),
    ("paraben-free", "Paraben-Free"),
    ("mineral-oil-free", "Mineral Oil-Free"),
    ("sulfate-free", "Sulfate-Free"),
    ("non-comedogenic", "Non-Comedogenic"),
    ("silicone-free", "Silicone-Free"),
    ("oil-free", "Oil-Free"),
    ("water-resistant", "Water Resistant"),
)

INGREDIENTS: tuple[tuple[str, str, str], ...] = (
    ("hyaluronic-acid", "Hyaluronic Acid", "Deep hydration and plumping"),
    ("niacinamide", "Niacinamide", "Balances sebum and brightens"),
    ("salicylic-acid", "Salicylic Acid", "Exfoliates inside the pore"),
    ("glycolic-acid", "Glycolic Acid", "AHA exfoliation"),
    ("lactic-acid", "Lactic Acid", "Gentle resurfacing"),
    ("retinol", "Retinol", "Addresses wrinkles and texture"),
    ("vitamin-c", "Vitamin C", "Brightening antioxidant"),
    ("vitamin-e", "Vitamin E", "Antioxidant support"),
    ("peptides", "Peptides", "Firming support"),
    ("ceramides", "Ceramides", "Reinforces skin barrier"),
    ("centella-asiatica", "Centella Asiatica", "Soothing repair"),
    ("snail-mucin", "Snail Mucin", "Hydrates and repairs"),
    ("squalane", "Squalane", "Lightweight moisture"),
    ("tea-tree", "Tea Tree", "Clarifying botanical"),
    ("green-tea", "Green Tea", "Antioxidant calming"),
    ("licorice-root", "Licorice Root", "Brightening botanical"),
    ("zinc-oxide", "Zinc Oxide", "Mineral UV filter"),
    ("titanium-dioxide", "Titanium Dioxide", "Physical sun protection"),
    ("bakuchiol", "Bakuchiol", "Retinol alternative"),
    ("panthenol", "Panthenol", "Humectant soothing"),
    ("propolis", "Propolis", "Calming antioxidant"),
    ("adenosine", "Adenosine", "Skin-smoothing"),
    ("tranexamic-acid", "Tranexamic Acid", "Targets discoloration"),
    ("alpha-arbutin", "Alpha Arbutin", "Fades dark spots"),
    ("fermented-yeast", "Galactomyces Ferment Filtrate", "Brightening ferment"),
    ("rice-extract", "Rice Extract", "Softens and brightens"),
    ("chamomile", "Chamomile", "Calming botanical"),
    ("calendula", "Calendula", "Soothing flower extract"),
    ("oatmeal", "Colloidal Oatmeal", "Comforts irritation"),
    ("shea-butter", "Shea Butter", "Rich emollient"),
    ("turmeric", "Turmeric Root Extract", "Brightening antioxidant support"),
)

INGREDIENT_NOTES: dict[str, dict[str, str]] = {
    "hyaluronic-acid": {
        "helps_with": "Draws moisture into skin layers to keep complexion bouncy and hydrated.",
        "avoid_with": "Strongly occlusive products that may trap bacteria without cleansing first.",
        "side_effects": "Rare; overuse without sealing moisture can lead to dryness in low humidity environments.",
    },
    "niacinamide": {
        "helps_with": "Balances oil production, strengthens barrier function, and refines pores.",
        "avoid_with": "Very low pH vitamin C serums in the same step to prevent potential irritation.",
        "side_effects": "May trigger temporary flushing in sensitive skin; start with lower concentrations.",
    },
    "salicylic-acid": {
        "helps_with": "Clears congestion inside pores and smooths rough texture.",
        "avoid_with": "Other strong exfoliating acids or topical retinoids in the same routine to reduce over-exfoliation.",
        "side_effects": "Dryness or mild peeling, especially if used too frequently.",
    },
    "retinol": {
        "helps_with": "Stimulates cell turnover to target wrinkles, texture, and post-acne marks.",
        "avoid_with": "Benzoyl peroxide or strong exfoliating acids in the same routine.",
        "side_effects": "Photosensitivity, dryness, and initial purging; always pair with SPF and moisturiser.",
    },
    "vitamin-c": {
        "helps_with": "Brightens skin tone, supports collagen, and defends against free radicals.",
        "avoid_with": "High pH niacinamide or direct acids immediately after application.",
        "side_effects": "Tingling or sensitivity, especially with high L-ascorbic acid concentrations.",
    },
    "centella-asiatica": {
        "helps_with": "Calms redness, supports wound healing, and reinforces the skin barrier.",
        "avoid_with": "No major conflicts; layer after actives to soothe.",
        "side_effects": "Rare; look for added essential oils that may irritate sensitive skin.",
    },
}

KOREAN_PRODUCTS: list[ProductSeed] = [
    ProductSeed(
        brand="COSRX",
        name="Advanced Snail 96 Mucin Power Essence",
        origin="KR",
        category="essence",
        price="24.00",
        currency="USD",
        summary="Lightweight essence that replenishes moisture with 96% snail secretion filtrate.",
        hero_ingredients="Snail mucin, hyaluronic acid, panthenol",
        rating=4.7,
        concerns=["dehydrated-skin", "damaged-skin-barrier", "redness"],
        ingredients=["snail-mucin", "hyaluronic-acid", "panthenol"],
        skin_types=["dry", "normal", "combination", "sensitive"],
        restrictions=["cruelty-free"],
        product_url="https://www.cosrx.com/products/advanced-snail-96-mucin-power-essence",
        image="https://img.lazcdn.com/g/p/c7cedae4b89dea2eb1d46f89fccc96b9.jpg_720x720q80.jpg",
    ),
    ProductSeed(
        brand="COSRX",
        name="Low pH Good Morning Gel Cleanser",
        origin="KR",
        category="cleanser",
        price="14.00",
        currency="USD",
        summary="Gentle daily gel cleanser that balances skin at a low pH.",
        hero_ingredients="Tea tree oil, betaine salicylate",
        rating=4.5,
        concerns=["acne-breakouts", "excess-oil", "uneven-skin-texture"],
        ingredients=["tea-tree", "salicylic-acid", "panthenol"],
        skin_types=["oily", "combination", "normal"],
        restrictions=["cruelty-free", "sulfate-free"],
        product_url="https://www.cosrx.com/products/low-ph-good-morning-gel-cleanser",
        image="https://s3.konvy.com/static/team/2025/0725/17534133699946.jpg",
    ),
    ProductSeed(
        brand="Laneige",
        name="Water Sleeping Mask",
        origin="KR",
        category="mask",
        price="29.00",
        currency="USD",
        summary="Overnight gel mask that hydrates and soothes tired skin.",
        hero_ingredients="Water science complex, squalane",
        rating=4.6,
        concerns=["dehydrated-skin", "dull-skin", "dryness"],
        ingredients=["hyaluronic-acid", "squalane", "green-tea"],
        skin_types=["dry", "normal", "combination"],
        restrictions=[],
        product_url="https://us.laneige.com/products/water-sleeping-mask",
        image="https://us.laneige.com/cdn/shop/files/WSM_AD_PDP_2.jpg?v=1754046790",
    ),
    ProductSeed(
        brand="Laneige",
        name="Cream Skin Refiner",
        origin="KR",
        category="toner",
        price="33.00",
        currency="USD",
        summary="Milky hydrating toner that comforts and strengthens the barrier.",
        hero_ingredients="White leaf tea water, amino acids",
        rating=4.7,
        concerns=["dryness", "dehydrated-skin", "sensitivity"],
        ingredients=["panthenol", "rice-extract", "green-tea"],
        skin_types=["dry", "normal", "sensitive"],
        restrictions=["alcohol-free"],
        product_url="https://us.laneige.com/products/cream-skin-toner-moisturizer",
        image="https://th.laneige.com/cdn/shop/files/1_HQ__Cream-Skin_cream-skin-E--product-artwork-Help-01_8700x8700_12131111_0.jpg?v=1761329251",
    ),
    ProductSeed(
        brand="Sulwhasoo",
        name="First Care Activating Serum",
        origin="KR",
        category="serum",
        price="89.00",
        currency="USD",
        summary="Balancing serum powered by Korean herbal blend to boost radiance.",
        hero_ingredients="Jaum balancing complex, licorice",
        rating=4.8,
        concerns=["dull-skin", "firmness", "uneven-skin-texture"],
        ingredients=["licorice-root", "fermented-yeast", "green-tea"],
        skin_types=["normal", "dry", "combination"],
        restrictions=[],
        product_url="https://us.sulwhasoo.com/products/first-care-activating-serum",
        image="https://th.sulwhasoo.com/cdn/shop/files/FCAS90.jpg?v=1759403827",
    ),
    ProductSeed(
        brand="Dr. Jart+",
        name="Cicapair Tiger Grass Color Correcting Treatment SPF 30",
        origin="KR",
        category="treatment",
        price="52.00",
        currency="USD",
        summary="Color-correcting cream that calms redness and protects with SPF 30.",
        hero_ingredients="Centella asiatica, herbs complex",
        rating=4.5,
        concerns=["redness", "sensitivity", "sun-protection"],
        ingredients=["centella-asiatica", "panthenol", "titanium-dioxide"],
        skin_types=["normal", "combination", "sensitive"],
        restrictions=["paraben-free"],
        product_url="https://us.drjart.com/products/cicapair-tiger-grass-color-correcting-treatment-spf-30",
        image="https://www.drjart.co.uk/media/export/cms/products/1000x1000/dj_sku_H58001_1000x1000_0.jpg",
    ),
    ProductSeed(
        brand="Dr. Jart+",
        name="Ceramidin Cream",
        origin="KR",
        category="moisturizer",
        price="48.00",
        currency="USD",
        summary="Rich cream infused with five ceramides to lock in moisture.",
        hero_ingredients="Ceramides, hyaluronic acid",
        rating=4.7,
        concerns=["damaged-skin-barrier", "dryness", "dehydrated-skin"],
        ingredients=["ceramides", "hyaluronic-acid", "panthenol"],
        skin_types=["dry", "normal", "sensitive"],
        restrictions=["paraben-free"],
        product_url="https://us.drjart.com/products/ceramidin-cream",
        image="https://lilabeauty.com.au/cdn/shop/products/buy-dr-jart-ceramidin-skin-barrier-moisturizing-cream-50ml-at-lila-beauty-korean-and-japanese-beauty-skin-care-210704.jpg?v=1704891552",
    ),
    ProductSeed(
        brand="Etude",
        name="SoonJung pH 5.5 Relief Toner",
        origin="KR",
        category="toner",
        price="19.00",
        currency="USD",
        summary="Low-irritant toner with panthenol and madecassoside for sensitive skin.",
        hero_ingredients="Panthenol, madecassoside",
        rating=4.6,
        concerns=["sensitivity", "damaged-skin-barrier", "redness"],
        ingredients=["panthenol", "centella-asiatica", "green-tea"],
        skin_types=["sensitive", "dry", "normal"],
        restrictions=["fragrance-free", "alcohol-free"],
        product_url="https://www.etude.com/us/en/products/soonjung-ph-55-relief-toner",
        image="https://www.mikaela-beauty.com/cdn/shop/files/AX6H2260w.jpg?v=1704945634",
    ),
    ProductSeed(
        brand="Innisfree",
        name="Green Tea Seed Serum",
        origin="KR",
        category="serum",
        price="30.00",
        currency="USD",
        summary="Hydrating serum with double-squeezed Jeju green tea and green tea seed oil.",
        hero_ingredients="Green tea, amino acids",
        rating=4.6,
        concerns=["dehydrated-skin", "dull-skin", "dryness"],
        ingredients=["green-tea", "hyaluronic-acid", "panthenol"],
        skin_types=["normal", "combination", "dry"],
        restrictions=["paraben-free"],
        product_url="https://us.innisfree.com/products/green-tea-seed-serum",
        image="https://main.thgimages.com/?url=https://static.thcdn.com/productimg/original/15227996-9175270721798909.jpg&format=webp&width=1500&height=1500&fit=cover",
    ),
    ProductSeed(
        brand="Banila Co",
        name="Clean It Zero Cleansing Balm Original",
        origin="KR",
        category="balm",
        price="22.00",
        currency="USD",
        summary="Sherbet cleansing balm that melts makeup without stripping skin.",
        hero_ingredients="Fruit extracts, vitamin C",
        rating=4.8,
        concerns=["excess-oil", "blackheads", "uneven-skin-texture"],
        ingredients=["vitamin-c", "squalane", "ceramides"],
        skin_types=["normal", "dry", "combination"],
        restrictions=["paraben-free"],
        product_url="https://banilausa.com/products/clean-it-zero-original-balancing-cleansing-balm",
        image="https://s3.konvy.com/static/team/2018/1022/15402028175352.jpg",
    ),
    ProductSeed(
        brand="SKIN1004",
        name="Madagascar Centella Ampoule",
        origin="KR",
        category="serum",
        price="28.00",
        currency="USD",
        summary="Pure centella asiatica ampoule from Madagascan leaves for calming hydration.",
        hero_ingredients="100% centella asiatica extract",
        rating=4.7,
        concerns=["redness", "sensitivity", "dehydrated-skin"],
        ingredients=["centella-asiatica", "panthenol"],
        skin_types=["sensitive", "normal", "combination", "dry"],
        restrictions=["vegan", "cruelty-free", "fragrance-free"],
        product_url="https://skin1004.com/products/madagascar-centella-ampoule",
        image="https://cdn11.bigcommerce.com/s-7p5jn6i1wf/images/stencil/670x670/products/1227/4463/skin1004-madagascar-centella-ampoule__98829.1725356484.jpg?c=1",
    ),
    ProductSeed(
        brand="Beauty of Joseon",
        name="Glow Serum: Propolis + Niacinamide",
        origin="KR",
        category="serum",
        price="17.00",
        currency="USD",
        summary="Honey-textured serum to soothe breakouts and refine pores.",
        hero_ingredients="Propolis, niacinamide",
        rating=4.8,
        concerns=["acne-breakouts", "large-pores", "dull-skin"],
        ingredients=["propolis", "niacinamide", "panthenol"],
        skin_types=["oily", "combination", "normal"],
        restrictions=["cruelty-free"],
        product_url="https://beautyofjoseon.com/products/glow-serum-propolis-niacinamide",
        image="https://www.koreanbeauty.se/cdn/shop/files/Glow_Serum_Propolis_Niacinamide.png?v=1758459963&width=1080",
    ),
    ProductSeed(
        brand="Round Lab",
        name="1025 Dokdo Toner",
        origin="KR",
        category="toner",
        price="25.00",
        currency="USD",
        summary="Mineral-rich toner sourced from Ulleungdo deep sea water for gentle exfoliation.",
        hero_ingredients="Sea water, beta-glucan",
        rating=4.6,
        concerns=["dehydrated-skin", "uneven-skin-texture", "sensitivity"],
        ingredients=["hyaluronic-acid", "panthenol", "licorice-root"],
        skin_types=["normal", "combination", "sensitive"],
        restrictions=["fragrance-free", "alcohol-free"],
        product_url="https://roundlabusa.com/products/1025-dokdo-toner",
        image="https://medias.watsons.co.th/publishing/WTCTH-297429-side-zoom.jpg",
    ),
    ProductSeed(
        brand="Mediheal",
        name="N.M.F Aquaring Ampoule Mask",
        origin="KR",
        category="mask",
        price="2.50",
        currency="USD",
        summary="Sheet mask delivering intense hydration with hyaluronic acid and NMF complex.",
        hero_ingredients="Hyaluronic acid, ceramides",
        rating=4.6,
        concerns=["dehydrated-skin", "dryness", "dull-skin"],
        ingredients=["hyaluronic-acid", "ceramides", "panthenol"],
        skin_types=["dry", "normal", "combination"],
        restrictions=["paraben-free"],
        product_url="https://mediheal.com/products/nmf-aquaring-ampoule-mask",
        image="https://m.media-amazon.com/images/I/51UHMN44bPL._AC_SL6000_.jpg",
    ),
    ProductSeed(
        brand="Dear, Klairs",
        name="Supple Preparation Unscented Toner",
        origin="KR",
        category="toner",
        price="22.00",
        currency="USD",
        summary="Fragrance-free hydrating toner that balances pH and preps skin.",
        hero_ingredients="Hyaluronic acid, centella",
        rating=4.7,
        concerns=["dehydrated-skin", "sensitivity", "redness"],
        ingredients=["hyaluronic-acid", "centella-asiatica", "panthenol"],
        skin_types=["sensitive", "dry", "normal"],
        restrictions=["fragrance-free", "vegan", "cruelty-free"],
        product_url="https://wishtrend.com/products/klairs-supple-preparation-unscented-toner",
        image="https://th.keautiful.com/cdn/shop/files/9b7edad28c9cd81cef40d8df4603378964950d8f4f06fbf6bcd2a2e206bb_grande.jpg?v=1686357821",
    ),
    ProductSeed(
        brand="Dear, Klairs",
        name="Freshly Juiced Vitamin C Drop",
        origin="KR",
        category="serum",
        price="23.00",
        currency="USD",
        summary="Gentle 5% vitamin C serum to brighten dull skin and fade spots.",
        hero_ingredients="Vitamin C, centella",
        rating=4.5,
        concerns=["hyperpigmentation", "dull-skin", "uneven-skin-texture"],
        ingredients=["vitamin-c", "licorice-root", "panthenol"],
        skin_types=["normal", "combination", "dry"],
        restrictions=["cruelty-free"],
        product_url="https://wishtrend.com/products/klairs-freshly-juiced-vitamin-c-drop",
        image="https://koreacosmeticsbn.com/cdn/shop/files/GOTADEVITAMINAENJUGORECIENTE.webp?v=1690696909&width=1946",
    ),
    ProductSeed(
        brand="Neogen",
        name="Real Ferment Micro Essence",
        origin="KR",
        category="essence",
        price="38.00",
        currency="USD",
        summary="Essence packed with 93% ferment complex to brighten and plump.",
        hero_ingredients="Bifida ferment, rice ferment",
        rating=4.6,
        concerns=["dull-skin", "dehydrated-skin", "fine-lines-wrinkles"],
        ingredients=["fermented-yeast", "rice-extract", "hyaluronic-acid"],
        skin_types=["normal", "dry", "combination"],
        restrictions=["alcohol-free"],
        product_url="https://neogenlab.us/products/real-ferment-micro-essence",
        image="https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/ngd/ngd44893/l/50.jpg",
    ),
    ProductSeed(
        brand="Missha",
        name="Time Revolution The First Treatment Essence",
        origin="KR",
        category="essence",
        price="54.00",
        currency="USD",
        summary="Iconic essence with fermented yeast to brighten and refine texture.",
        hero_ingredients="Yeast ferment, niacinamide",
        rating=4.7,
        concerns=["dull-skin", "hyperpigmentation", "fine-lines-wrinkles"],
        ingredients=["fermented-yeast", "niacinamide", "adenosine"],
        skin_types=["normal", "combination", "dry"],
        restrictions=["paraben-free"],
        product_url="https://misshaus.com/products/time-revolution-the-first-treatment-essence",
        image="https://inwfile.com/s-fk/87w46p.jpg",
    ),
    ProductSeed(
        brand="Dr. G",
        name="Red Blemish Clear Soothing Cream",
        origin="KR",
        category="moisturizer",
        price="36.00",
        currency="USD",
        summary="Cooling gel-cream to calm irritation and strengthen barrier.",
        hero_ingredients="Centella complex, hyaluronic acid",
        rating=4.6,
        concerns=["acne-breakouts", "redness", "sensitivity"],
        ingredients=["centella-asiatica", "niacinamide", "hyaluronic-acid"],
        skin_types=["oily", "combination", "sensitive"],
        restrictions=["fragrance-free", "alcohol-free"],
        product_url="https://dr-g.com/products/red-blemish-clear-soothing-cream",
        image="https://img.lazcdn.com/g/p/f25f0ddad7df1e5512fc41a83079912d.jpg_720x720q80.jpg",
    ),
    ProductSeed(
        brand="AXIS-Y",
        name="Dark Spot Correcting Glow Serum",
        origin="KR",
        category="serum",
        price="22.00",
        currency="USD",
        summary="Brightening serum with niacinamide and plant extracts to fade spots.",
        hero_ingredients="Niacinamide, squalane",
        rating=4.6,
        concerns=["hyperpigmentation", "dull-skin", "blemishes"],
        ingredients=["niacinamide", "squalane", "alpha-arbutin"],
        skin_types=["normal", "combination", "oily"],
        restrictions=["vegan", "cruelty-free"],
        product_url="https://axis-y.com/products/dark-spot-correcting-glow-serum",
        image="https://s3.konvy.com/static/team/2023/0705/16885262857889.jpg",
    ),
    ProductSeed(
        brand="I'm From",
        name="Mugwort Essence",
        origin="KR",
        category="essence",
        price="40.00",
        currency="USD",
        summary="Single ingredient mugwort essence to calm and purify stressed skin.",
        hero_ingredients="Artemisia princeps extract",
        rating=4.7,
        concerns=["redness", "sensitivity", "acne-breakouts"],
        ingredients=["chamomile", "green-tea"],
        skin_types=["sensitive", "normal", "combination"],
        restrictions=["vegan"],
        product_url="https://wishtrend.com/products/im-from-mugwort-essence",
        image="https://lilabeauty.com.au/cdn/shop/products/buy-im-from-mugwort-essence-160ml-at-lila-beauty-korean-and-japanese-beauty-skin-care-511518.jpg?v=1636559238",
    ),
    ProductSeed(
        brand="Illiyoon",
        name="Ceramide Ato Concentrate Cream",
        origin="KR",
        category="moisturizer",
        price="28.00",
        currency="USD",
        summary="Hypoallergenic cream that strengthens a compromised barrier.",
        hero_ingredients="Ceramide capsule, shea butter",
        rating=4.8,
        concerns=["damaged-skin-barrier", "dryness", "sensitivity"],
        ingredients=["ceramides", "shea-butter", "panthenol"],
        skin_types=["dry", "normal", "sensitive"],
        restrictions=["fragrance-free"],
        product_url="https://global.amorepacific.com/products/illiyoon-ceramide-ato-concentrate-cream",
        image="https://lilabeauty.com.au/cdn/shop/files/Ceramide_ATO_Concentrate_Cream_230ml.jpg?v=1749675684",
    ),
    ProductSeed(
        brand="Make P:rem",
        name="Safe Me Relief Moisture Cream 12",
        origin="KR",
        category="moisturizer",
        price="29.00",
        currency="USD",
        summary="Minimal ingredient cream to soothe sensitive, irritated skin.",
        hero_ingredients="Squalane, glycerin",
        rating=4.6,
        concerns=["sensitivity", "dryness", "damaged-skin-barrier"],
        ingredients=["squalane", "hyaluronic-acid", "panthenol"],
        skin_types=["sensitive", "dry", "normal"],
        restrictions=["fragrance-free", "alcohol-free"],
        product_url="https://makeprem.us/products/safe-me-relief-moisture-cream",
        image="https://i0.wp.com/olpeo.mk/wp-content/uploads/safe-me.-relief-moisture-cream12-at-olpeo-korean-skincare-store.png?fit=1080%2C1080&ssl=1",
    ),
    ProductSeed(
        brand="Pyunkang Yul",
        name="Moisture Ampoule",
        origin="KR",
        category="serum",
        price="28.00",
        currency="USD",
        summary="Viscous ampoule that locks in moisture with minimal ingredients.",
        hero_ingredients="Astragalus membranaceus root extract",
        rating=4.5,
        concerns=["dehydrated-skin", "dryness", "dull-skin"],
        ingredients=["panthenol", "adenosine", "squalane"],
        skin_types=["dry", "normal", "combination"],
        restrictions=["fragrance-free", "paraben-free"],
        product_url="https://pyunkangyul.us/products/moisture-ampoule",
        image="https://lilabeauty.com.au/cdn/shop/products/PyunkangYulMoistureAmpoule100ml.jpg?v=1636539697",
    ),
    ProductSeed(
        brand="Huxley",
        name="Secret of Sahara Oil Essence",
        origin="KR",
        category="essence",
        price="58.00",
        currency="USD",
        summary="Bi-phase oil essence to hydrate and protect against environmental stress.",
        hero_ingredients="Prickly pear seed oil, cactus extract",
        rating=4.4,
        concerns=["dull-skin", "dryness", "firmness"],
        ingredients=["squalane", "green-tea", "licorice-root"],
        skin_types=["dry", "normal", "combination"],
        restrictions=["paraben-free"],
        product_url="https://huxleyworld.com/products/oil-essence-secret-of-sahara",
        image="https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/hux/hux53396/l/35.jpg",
    ),
]

JAPANESE_PRODUCTS: list[ProductSeed] = [
    ProductSeed(
        brand="Shiseido",
        name="Ultimune Power Infusing Concentrate",
        origin="JP",
        category="serum",
        price="140.00",
        currency="USD",
        summary="Signature anti-aging serum that strengthens skin's defenses and boosts radiance.",
        hero_ingredients="ImuGenerationRED technology, reishi mushroom",
        rating=4.7,
        concerns=["dull-skin", "firmness", "fine-lines-wrinkles"],
        ingredients=["fermented-yeast", "green-tea", "vitamin-e"],
        skin_types=["normal", "dry", "combination"],
        restrictions=[],
        product_url="https://www.shiseido.com/ultimune-power-infusing-concentrate",
        image="https://www.shiseido.co.th/dw/image/v2/BCSK_PRD/on/demandware.static/-/Sites-itemmaster_shiseido/default/dwd9b6b41c/images/products/22390/22390_S_01.jpg?sw=1000&sh=1000&sm=fit",
    ),
    ProductSeed(
        brand="Hada Labo",
        name="Gokujyun Hyaluronic Acid Lotion",
        origin="JP",
        category="toner",
        price="15.00",
        currency="USD",
        summary="Cult-favorite lotion packed with multiple hyaluronic acids for lasting hydration.",
        hero_ingredients="Super hyaluronic acid blend",
        rating=4.8,
        concerns=["dehydrated-skin", "dryness", "dull-skin"],
        ingredients=["hyaluronic-acid", "panthenol", "ceramides"],
        skin_types=["dry", "normal", "combination", "sensitive"],
        restrictions=["fragrance-free", "alcohol-free"],
        product_url="https://www.hadalabo.jp/en/products/hadalabo-gokujyun-lotion",
        image="https://lilabeauty.com.au/cdn/shop/products/RohtoHadaLaboGokujyunHyaluronicAcidLotionMoist170ml.jpg?v=1636528019",
    ),
    ProductSeed(
        brand="SK-II",
        name="Facial Treatment Essence",
        origin="JP",
        category="essence",
        price="185.00",
        currency="USD",
        summary="Iconic essence with 90% PITERA™ to refine texture and enhance clarity.",
        hero_ingredients="Pitera ferment essence",
        rating=4.8,
        concerns=["dull-skin", "hyperpigmentation", "fine-lines-wrinkles"],
        ingredients=["fermented-yeast", "niacinamide", "vitamin-e"],
        skin_types=["normal", "dry", "combination"],
        restrictions=[],
        product_url="https://www.sk-ii.com/product/facial-treatment-essence",
        image="https://www.konvy.com/static/team/2023/0222/16770521617283_600x600.jpg",
    ),
    ProductSeed(
        brand="Biore",
        name="UV Aqua Rich Watery Essence SPF 50+",
        origin="JP",
        category="sunscreen",
        price="16.00",
        currency="USD",
        summary="Lightweight chemical sunscreen that leaves a fresh, invisible finish.",
        hero_ingredients="Hyaluronic acid, royal jelly extract",
        rating=4.7,
        concerns=["sun-protection", "dehydrated-skin", "excess-oil"],
        ingredients=["hyaluronic-acid", "vitamin-e", "panthenol"],
        skin_types=["oily", "combination", "normal"],
        restrictions=["water-resistant"],
        product_url="https://www.kao.co.jp/bioreuv/aquarich/wateryessence/",
        image="https://s3.konvy.com/static/team/2024/0503/17147356019660.jpg",
    ),
    ProductSeed(
        brand="Kose",
        name="Sekkisei Emulsion",
        origin="JP",
        category="moisturizer",
        price="60.00",
        currency="USD",
        summary="Brightening emulsion with oriental plant extracts to hydrate and refine tone.",
        hero_ingredients="Coix seed, angelica, melothria",
        rating=4.5,
        concerns=["hyperpigmentation", "dull-skin", "dryness"],
        ingredients=["licorice-root", "rice-extract", "vitamin-e"],
        skin_types=["normal", "dry", "combination"],
        restrictions=[],
        product_url="https://www.kose.co.jp/sekkisei/en/products/emulsion/",
        image="https://s3.konvy.com/static/team/2024/1115/17316657228677.jpg",
    ),
    ProductSeed(
        brand="DHC",
        name="Deep Cleansing Oil",
        origin="JP",
        category="oil",
        price="30.00",
        currency="USD",
        summary="Olive oil-based cleansing oil that dissolves makeup while nourishing skin.",
        hero_ingredients="Olive oil, vitamin E",
        rating=4.8,
        concerns=["blackheads", "excess-oil", "uneven-skin-texture"],
        ingredients=["squalane", "vitamin-e", "licorice-root"],
        skin_types=["normal", "dry", "combination"],
        restrictions=["paraben-free"],
        product_url="https://www.dhccare.com/deep-cleansing-oil",
        image="https://s3.konvy.com/static/team/2023/0828/16932048288541_600x600.jpg",
    ),
    ProductSeed(
        brand="Sofina",
        name="iP Base Care Serum",
        origin="JP",
        category="serum",
        price="55.00",
        currency="USD",
        summary="Carbonated micro-bubble serum to boost absorption of subsequent skincare.",
        hero_ingredients="Carbonic acid foam, glycerin",
        rating=4.6,
        concerns=["dull-skin", "dehydrated-skin", "firmness"],
        ingredients=["hyaluronic-acid", "niacinamide", "panthenol"],
        skin_types=["normal", "combination", "dry"],
        restrictions=[],
        product_url="https://www.sofina.co.jp/ip/en/product/basecare/",
        image="https://www.jeban.com/uploads/reviews/product/113291/111668_015993dd74.jpg",
    ),
    ProductSeed(
        brand="Curel",
        name="Intensive Moisture Cream",
        origin="JP",
        category="moisturizer",
        price="28.00",
        currency="USD",
        summary="Gentle ceramide cream formulated for sensitive, dry skin.",
        hero_ingredients="Ceramide function complex, eucalyptus",
        rating=4.7,
        concerns=["dryness", "damaged-skin-barrier", "sensitivity"],
        ingredients=["ceramides", "panthenol", "squalane"],
        skin_types=["dry", "normal", "sensitive"],
        restrictions=["fragrance-free", "alcohol-free"],
        product_url="https://www.curel.com/jp/en/face/creams/intensive-moisture-cream",
        image="https://medias.watsons.co.th/publishing/WTCTH-265683-front-zoom.jpg?version=1733525570",
    ),
    ProductSeed(
        brand="Muji",
        name="Sensitive Skin Toning Water High Moisture",
        origin="JP",
        category="toner",
        price="16.00",
        currency="USD",
        summary="Soothing toning water infused with Japanese hot spring water for delicate skin.",
        hero_ingredients="Grapefruit seed extract, hyaluronic acid",
        rating=4.5,
        concerns=["sensitivity", "dehydrated-skin", "redness"],
        ingredients=["hyaluronic-acid", "panthenol", "green-tea"],
        skin_types=["sensitive", "dry", "normal"],
        restrictions=["fragrance-free", "alcohol-free"],
        product_url="https://www.muji.us/store/sensitive-skin-toning-water-high-moisture.html",
        image="https://www.jeban.com/uploads/reviews/product/86573/517629_e3f169337d.jpg",
    ),
    ProductSeed(
        brand="Rohto",
        name="Melano CC Intensive Anti-Spot Essence",
        origin="JP",
        category="treatment",
        price="18.00",
        currency="USD",
        summary="Targeted vitamin C essence to fade dark spots and prevent future blemishes.",
        hero_ingredients="Vitamin C derivative, vitamin E",
        rating=4.6,
        concerns=["hyperpigmentation", "blemishes", "dull-skin"],
        ingredients=["vitamin-c", "vitamin-e", "licorice-root"],
        skin_types=["normal", "combination", "oily"],
        restrictions=[],
        product_url="https://jp.rohto.com/melanocc/products/essence/",
        image="https://lilabeauty.com.au/cdn/shop/products/RohtoMelanoCCAntiSpotIntensiveEssenceRenew20ml_700x.jpg?v=1636527885",
    ),
    ProductSeed(
        brand="Ipsa",
        name="The Time Reset Aqua",
        origin="JP",
        category="toner",
        price="70.00",
        currency="USD",
        summary="Hydrating toner that replenishes moisture and refines texture.",
        hero_ingredients="Aqua presenter, sodium hyaluronate",
        rating=4.6,
        concerns=["dehydrated-skin", "dull-skin", "uneven-skin-texture"],
        ingredients=["hyaluronic-acid", "niacinamide", "panthenol"],
        skin_types=["normal", "combination", "dry"],
        restrictions=[],
        product_url="https://www.ipsa.co.jp/en/product/time-reset-aqua",
        image="https://s3.konvy.com/static/team/2021/0429/16196875142792.jpg",
    ),
    ProductSeed(
        brand="Obagi",
        name="C10 Serum",
        origin="JP",
        category="serum",
        price="80.00",
        currency="USD",
        summary="10% vitamin C serum that brightens tone and tightens pores.",
        hero_ingredients="Pure vitamin C, vitamin E",
        rating=4.5,
        concerns=["hyperpigmentation", "large-pores", "dull-skin"],
        ingredients=["vitamin-c", "vitamin-e", "panthenol"],
        skin_types=["normal", "combination", "oily"],
        restrictions=[],
        product_url="https://www.obagi.co.jp/products/c10-serum/",
        image="https://product.hstatic.net/1000241635/product/c20_04_66a1b5ff7bc846a7bbb468e0216d6c3d.jpg",
    ),
    ProductSeed(
        brand="Kose",
        name="Sekkisei Treatment Cleansing Oil",
        origin="JP",
        category="oil",
        price="30.00",
        currency="USD",
        summary="Luxurious cleansing oil that removes makeup while brightening dull skin.",
        hero_ingredients="Rice bran oil, oriental herb extracts",
        rating=4.5,
        concerns=["dull-skin", "blackheads", "excess-oil"],
        ingredients=["rice-extract", "vitamin-e", "licorice-root"],
        skin_types=["normal", "dry", "combination"],
        restrictions=[],
        product_url="https://www.kose.co.jp/sekkisei/en/products/cleansing-oil/",
        image="https://sekkiseibeauty.com/cdn/shop/files/1_cbdc68c8-dfc0-4610-83f9-28145cfaa26a.png?v=1753036793",
    ),
    ProductSeed(
        brand="Anessa",
        name="Perfect UV Sunscreen Skincare Milk SPF 50+",
        origin="JP",
        category="sunscreen",
        price="35.00",
        currency="USD",
        summary="Silky water-resistant sunscreen that protects while caring for skin.",
        hero_ingredients="Thermo booster tech, hyaluronic acid",
        rating=4.7,
        concerns=["sun-protection", "dehydrated-skin", "firmness"],
        ingredients=["titanium-dioxide", "hyaluronic-acid", "green-tea"],
        skin_types=["normal", "combination", "oily"],
        restrictions=["water-resistant"],
        product_url="https://www.shiseido.com/anessa-perfect-uv-sunscreen-skincare-milk",
        image="https://s3.konvy.com/static/team/2024/0227/17090199639894.jpg",
    ),
    ProductSeed(
        brand="Senka",
        name="Perfect Whip Cleansing Foam",
        origin="JP",
        category="cleanser",
        price="10.00",
        currency="USD",
        summary="Dense foaming cleanser that removes impurities without tightness.",
        hero_ingredients="Silk essence, hyaluronic acid",
        rating=4.6,
        concerns=["excess-oil", "blackheads", "uneven-skin-texture"],
        ingredients=["hyaluronic-acid", "green-tea", "panthenol"],
        skin_types=["normal", "combination", "oily"],
        restrictions=[],
        product_url="https://www.shiseido.com/senka-perfect-whip",
        image="https://www.konvy.com/static/team/2023/0505/16832796673849_600x600.jpg",
    ),
    ProductSeed(
        brand="Hada Labo",
        name="Gokujyun Premium Whitening Lotion",
        origin="JP",
        category="toner",
        price="18.00",
        currency="USD",
        summary="Hydrating lotion with tranexamic acid to even tone and boost clarity.",
        hero_ingredients="Tranexamic acid, hyaluronic acid",
        rating=4.6,
        concerns=["hyperpigmentation", "dehydrated-skin", "dull-skin"],
        ingredients=["tranexamic-acid", "hyaluronic-acid", "panthenol"],
        skin_types=["normal", "dry", "combination"],
        restrictions=["fragrance-free"],
        product_url="https://www.hadalabo.jp/en/products/premium-whitening-lotion",
        image="https://buymejapan.com/cdn/shop/products/png_20230417_204338_0000.webp?v=1742294517",
    ),
    ProductSeed(
        brand="Naturie",
        name="Hatomugi Skin Conditioner",
        origin="JP",
        category="toner",
        price="14.00",
        currency="USD",
        summary="Multi-use lotion with job's tears extract to hydrate and soothe.",
        hero_ingredients="Hatomugi barley extract",
        rating=4.5,
        concerns=["dehydrated-skin", "redness", "dull-skin"],
        ingredients=["rice-extract", "panthenol", "green-tea"],
        skin_types=["normal", "combination", "sensitive"],
        restrictions=["fragrance-free"],
        product_url="https://www.naturie-net.jp/en/products/skin-conditioner/",
        image="https://lilabeauty.com.au/cdn/shop/products/buy-i-mju-naturie-hatomugi-skin-conditioner-500ml-at-lila-beauty-korean-and-japanese-beauty-skin-care-643839.jpg?v=1636811729",
    ),
    ProductSeed(
        brand="Suqqu",
        name="Moisture Rich Mask",
        origin="JP",
        category="mask",
        price="85.00",
        currency="USD",
        summary="Creamy leave-on mask to restore suppleness and luminosity overnight.",
        hero_ingredients="Botanical oils, hyaluronic acid",
        rating=4.6,
        concerns=["dryness", "dull-skin", "firmness"],
        ingredients=["squalane", "hyaluronic-acid", "vitamin-e"],
        skin_types=["dry", "normal", "combination"],
        restrictions=[],
        product_url="https://www.suqqu.com/product/moisture-rich-mask",
        image="https://down-th.img.susercontent.com/file/th-11134207-23020-fgxasp1yrznva3",
    ),
    ProductSeed(
        brand="Lululun",
        name="Precious Red Face Mask",
        origin="JP",
        category="mask",
        price="28.00",
        currency="USD",
        summary="Daily anti-aging sheet mask targeted at hydration and elasticity.",
        hero_ingredients="Rice ferment, pomegranate",
        rating=4.5,
        concerns=["fine-lines-wrinkles", "dryness", "dull-skin"],
        ingredients=["fermented-yeast", "rice-extract", "vitamin-e"],
        skin_types=["normal", "dry", "combination"],
        restrictions=["paraben-free"],
        product_url="https://lululun.com/products/precious-red",
        image="https://www.konvy.com/static/team/2024/0214/17079097191892_600x600.jpg",
    ),
    ProductSeed(
        brand="Biore",
        name="UV Athlizm Skin Protect Essence SPF 50+",
        origin="JP",
        category="sunscreen",
        price="22.00",
        currency="USD",
        summary="High-performance sunscreen that withstands heat, water, and sweat.",
        hero_ingredients="Micro defense formula, hyaluronic acid",
        rating=4.7,
        concerns=["sun-protection", "excess-oil", "dehydrated-skin"],
        ingredients=["hyaluronic-acid", "vitamin-e", "panthenol"],
        skin_types=["oily", "combination", "normal"],
        restrictions=["water-resistant"],
        product_url="https://www.kao.co.jp/bioreuv/athlizm/essence/",
        image="https://inwfile.com/s-fk/834nf7.jpg",
    ),
]

THAI_PRODUCTS: list[ProductSeed] = [
    ProductSeed(
        brand="Snail White",
        name="Whipp Soap",
        origin="TH",
        category="cleanser",
        price="12.00",
        currency="USD",
        summary="Rich foaming facial soap infused with snail secretion to brighten and soften.",
        hero_ingredients="Snail filtrate, niacinamide",
        rating=4.4,
        concerns=["acne-breakouts", "dull-skin", "uneven-skin-texture"],
        ingredients=["snail-mucin", "niacinamide", "licorice-root"],
        skin_types=["normal", "oily", "combination"],
        restrictions=[],
        product_url="https://www.snailwhite.co.th/products/whipp-soap",
        image="https://www.cosmenet.in.th/upload/iblock/b46/snailwhite-whipp-soap-600.jpg",
    ),
    ProductSeed(
        brand="Snail White",
        name="Miracle Intensive Repair Serum",
        origin="TH",
        category="serum",
        price="42.00",
        currency="USD",
        summary="Brightening serum that repairs skin with snail secretion filtrate and botanical actives.",
        hero_ingredients="Snail mucin, vitamin C",
        rating=4.5,
        concerns=["hyperpigmentation", "dull-skin", "damaged-skin-barrier"],
        ingredients=["snail-mucin", "vitamin-c", "niacinamide"],
        skin_types=["normal", "combination", "dry"],
        restrictions=[],
        product_url="https://www.snailwhite.co.th/products/miracle-intensive-repair-serum",
        image="https://www.cosmenet.in.th/upload/iblock/bba/snailwhite-miracle-intensive-repair-600.jpg",
    ),
    ProductSeed(
        brand="Mistine",
        name="Aqua Base Sunscreen SPF 50 PA++++",
        origin="TH",
        category="sunscreen",
        price="18.00",
        currency="USD",
        summary="Daily sunscreen with a weightless aqua texture for humid climates.",
        hero_ingredients="Hyaluronic acid, vitamin E",
        rating=4.3,
        concerns=["sun-protection", "dehydrated-skin", "excess-oil"],
        ingredients=["hyaluronic-acid", "vitamin-e", "titanium-dioxide"],
        skin_types=["oily", "combination", "normal"],
        restrictions=["water-resistant"],
        product_url="https://mistine.com/product/aqua-base-sunscreen",
        image="https://cdn.thebeautrium.com/image-product/B0065696.webp",
    ),
    ProductSeed(
        brand="Mistine",
        name="Acne Clear Facial Foam",
        origin="TH",
        category="cleanser",
        price="10.00",
        currency="USD",
        summary="Foaming cleanser with tea tree to cleanse pores and reduce breakouts.",
        hero_ingredients="Tea tree, salicylic acid",
        rating=4.2,
        concerns=["acne-breakouts", "excess-oil", "blackheads"],
        ingredients=["tea-tree", "salicylic-acid", "panthenol"],
        skin_types=["oily", "combination"],
        restrictions=[],
        product_url="https://mistine.com/product/acne-clear-facial-foam",
        image="https://th-test-11.slatic.net/p/238900cf380cd179ddc24f8d4b052904.jpg",
    ),
    ProductSeed(
        brand="Smooth E",
        name="Babyface Gel",
        origin="TH",
        category="cleanser",
        price="15.00",
        currency="USD",
        summary="Soap-free gel cleanser that soothes sensitive and acne-prone skin.",
        hero_ingredients="Vitamin E, aloe vera",
        rating=4.4,
        concerns=["sensitivity", "redness", "acne-breakouts"],
        ingredients=["vitamin-e", "green-tea", "chamomile"],
        skin_types=["sensitive", "normal", "oily"],
        restrictions=["fragrance-free"],
        product_url="https://www.smootheglobal.com/en/products/babyface-gel",
        image="https://smooth-e.com/cdn/shop/files/1.5.png?v=1745901001",
    ),
    ProductSeed(
        brand="Smooth E",
        name="White Babyface Serum",
        origin="TH",
        category="serum",
        price="32.00",
        currency="USD",
        summary="Brightening serum targeting dark spots with stabilized vitamin C.",
        hero_ingredients="Vitamin C, licorice",
        rating=4.3,
        concerns=["hyperpigmentation", "dull-skin", "uneven-skin-texture"],
        ingredients=["vitamin-c", "licorice-root", "niacinamide"],
        skin_types=["normal", "combination", "dry"],
        restrictions=[],
        product_url="https://www.smootheglobal.com/en/products/white-babyface-serum",
        image="https://s3.konvy.com/static/team/2020/1101/16042316446368.jpg",
    ),
    ProductSeed(
        brand="Cute Press",
        name="1st Skin Booster Serum",
        origin="TH",
        category="serum",
        price="28.00",
        currency="USD",
        summary="Pre-serum booster with concentrated vitamins to energize skin.",
        hero_ingredients="Niacinamide, hyaluronic acid",
        rating=4.4,
        concerns=["dull-skin", "dehydrated-skin", "firmness"],
        ingredients=["niacinamide", "hyaluronic-acid", "panthenol"],
        skin_types=["normal", "combination", "dry"],
        restrictions=[],
        product_url="https://cutepress.com/products/1st-skin-booster-serum",
        image="https://global.cutepress.com/cdn/shop/files/2021-new-product_picture-dropper_serum-1000x1000--16.jpg?v=1715913659&width=1200",
    ),
    ProductSeed(
        brand="Cute Press",
        name="UV Expert Protection White & Matte SPF 50+",
        origin="TH",
        category="sunscreen",
        price="20.00",
        currency="USD",
        summary="Matte finish sunscreen that controls shine and brightens complexion.",
        hero_ingredients="Niacinamide, sebum control powder",
        rating=4.3,
        concerns=["sun-protection", "excess-oil", "hyperpigmentation"],
        ingredients=["niacinamide", "zinc-oxide", "vitamin-e"],
        skin_types=["oily", "combination"],
        restrictions=[],
        product_url="https://cutepress.com/products/uv-expert-protection-white-matte",
        image="https://www.cutepress.com/pub/media/catalog/product/cache/8bcb7669b359307340d2dd48787afbce/p/r/product_picture_sep-a-10.jpg",
    ),
    ProductSeed(
        brand="BK Acne",
        name="Serum Brightening Anti-Pollution",
        origin="TH",
        category="serum",
        price="22.00",
        currency="USD",
        summary="Light oil-free serum targeting blemishes while shielding against pollution.",
        hero_ingredients="Tea tree, niacinamide",
        rating=4.2,
        concerns=["acne-breakouts", "blemishes", "dull-skin"],
        ingredients=["tea-tree", "niacinamide", "panthenol"],
        skin_types=["oily", "combination", "normal"],
        restrictions=["oil-free"],
        product_url="https://www.bkacne.com/products/serum-brightening-anti-pollution",
        image="https://s3.konvy.com/static/team/2019/0628/15617157029527.jpg",
    ),
    ProductSeed(
        brand="Yanhee",
        name="Vitamin C Serum",
        origin="TH",
        category="serum",
        price="18.00",
        currency="USD",
        summary="Clinic-formulated vitamin C serum to lighten dark spots and restore glow.",
        hero_ingredients="Vitamin C, arbutin",
        rating=4.1,
        concerns=["hyperpigmentation", "dull-skin", "blemishes"],
        ingredients=["vitamin-c", "alpha-arbutin", "tranexamic-acid"],
        skin_types=["normal", "combination", "dry"],
        restrictions=[],
        product_url="https://www.yanheeproduct.com/products/vitamin-c-serum",
        image="https://s3.konvy.com/static/team/2021/0112/16104579772534.jpg",
    ),
]

GLOBAL_PRODUCTS: list[ProductSeed] = [
    ProductSeed(
        brand="The Ordinary",
        name="Niacinamide 10% + Zinc 1%",
        origin="CA",
        category="serum",
        price="6.50",
        currency="USD",
        summary="High-strength vitamin and mineral blemish formula to balance sebum and minimize pores.",
        hero_ingredients="Niacinamide, zinc PCA",
        rating=4.6,
        concerns=["acne-breakouts", "large-pores", "excess-oil"],
        ingredients=["niacinamide", "salicylic-acid", "panthenol"],
        skin_types=["oily", "combination", "normal"],
        restrictions=["cruelty-free"] ,
        product_url="https://theordinary.com/product/niacinamide-10-zinc-1",
        image="https://medias.watsons.co.th/publishing/WTCTH-320290-side-zoom.jpg?version=1754940611",
    ),
    ProductSeed(
        brand="The Ordinary",
        name="Hyaluronic Acid 2% + B5",
        origin="CA",
        category="serum",
        price="7.50",
        currency="USD",
        summary="Hydration-supporting serum with multi-weight hyaluronic acid and provitamin B5.",
        hero_ingredients="Hyaluronic acid, vitamin B5",
        rating=4.7,
        concerns=["dehydrated-skin", "dryness", "dull-skin"],
        ingredients=["hyaluronic-acid", "panthenol", "squalane"],
        skin_types=["dry", "normal", "combination", "sensitive"],
        restrictions=["vegan", "cruelty-free"] ,
        product_url="https://theordinary.com/product/hyaluronic-acid-2-b5",
        image="https://www.adorebeauty.com.au/pim_media/000/558/165/PNG_1_O._Hyaluronic_Acid_thirty.png?fmt=webp&w=980&h=980",
    ),
    ProductSeed(
        brand="The Ordinary",
        name="AHA 30% + BHA 2% Peeling Solution",
        origin="CA",
        category="treatment",
        price="9.50",
        currency="USD",
        summary="Weekly exfoliating facial to fight visible blemishes and improve radiance.",
        hero_ingredients="Glycolic acid, salicylic acid",
        rating=4.5,
        concerns=["uneven-skin-texture", "blackheads", "dull-skin"],
        ingredients=["glycolic-acid", "salicylic-acid", "lactic-acid"],
        skin_types=["normal", "oily", "combination"],
        restrictions=["vegan", "cruelty-free"] ,
        product_url="https://theordinary.com/product/aha-30-bha-2-peeling-solution",
        image="https://molecule.lt/image/cache/aha-30-bha-2-sveiciamasis-tirpalas_202209281720541-1000x1000.jpg",
    ),
    ProductSeed(
        brand="Paula's Choice",
        name="Skin Perfecting 2% BHA Liquid Exfoliant",
        origin="US",
        category="treatment",
        price="34.00",
        currency="USD",
        summary="Leave-on exfoliant that unclogs pores and smooths wrinkles with salicylic acid.",
        hero_ingredients="Salicylic acid, green tea",
        rating=4.8,
        concerns=["acne-breakouts", "blackheads", "large-pores"],
        ingredients=["salicylic-acid", "green-tea", "panthenol"],
        skin_types=["oily", "combination", "normal"],
        restrictions=["cruelty-free", "fragrance-free"] ,
        product_url="https://www.paulaschoice.com/skin-perfecting-2-bha-liquid-exfoliant",
        image="https://paulaschoice.th/cdn/shop/files/2_-bha-liquid-exfoliant-118ml_04dbf576-3500-4ae8-8a6f-ec5467351522_720x.jpg?v=1751516088",
    ),
    ProductSeed(
        brand="Paula's Choice",
        name="10% Niacinamide Booster",
        origin="US",
        category="serum",
        price="49.00",
        currency="USD",
        summary="Concentrated niacinamide booster to tighten pores and brighten tone.",
        hero_ingredients="Niacinamide, vitamin C",
        rating=4.7,
        concerns=["large-pores", "dull-skin", "uneven-skin-texture"],
        ingredients=["niacinamide", "vitamin-c", "panthenol"],
        skin_types=["normal", "combination", "oily"],
        restrictions=["cruelty-free", "fragrance-free"] ,
        product_url="https://www.paulaschoice.com/10-niacinamide-booster",
        image="https://paulaschoice.th/cdn/shop/files/10percent-niacinamide-booster-paula-s-choice-malaysia-1_c60adb56-214e-4608-930e-9440102efdee_1080x.jpg?v=1726072653",
    ),
    ProductSeed(
        brand="CeraVe",
        name="Foaming Facial Cleanser",
        origin="US",
        category="cleanser",
        price="16.00",
        currency="USD",
        summary="Non-drying foaming cleanser with ceramides to remove excess oil and makeup.",
        hero_ingredients="Ceramides, niacinamide",
        rating=4.7,
        concerns=["excess-oil", "acne-breakouts", "uneven-skin-texture"],
        ingredients=["ceramides", "niacinamide", "panthenol"],
        skin_types=["oily", "combination", "normal"],
        restrictions=["fragrance-free", "non-comedogenic"] ,
        product_url="https://www.cerave.com/skincare/cleansers/foaming-facial-cleanser",
        image="https://inwfile.com/s-cv/e2l0fx.png",
    ),
    ProductSeed(
        brand="CeraVe",
        name="Hydrating Facial Cleanser",
        origin="US",
        category="cleanser",
        price="16.00",
        currency="USD",
        summary="Creamy cleanser that removes impurities while hydrating and restoring the barrier.",
        hero_ingredients="Ceramides, hyaluronic acid",
        rating=4.8,
        concerns=["dryness", "dehydrated-skin", "sensitivity"],
        ingredients=["ceramides", "hyaluronic-acid", "panthenol"],
        skin_types=["dry", "normal", "sensitive"],
        restrictions=["fragrance-free", "non-comedogenic"] ,
        product_url="https://www.cerave.com/skincare/cleansers/hydrating-facial-cleanser",
        image="https://www.essentials.lk/cdn/shop/files/CeraveHydratingFacialCleanserForNormalToDrySkin237ml.jpg?v=1734173420",
    ),
    ProductSeed(
        brand="CeraVe",
        name="Moisturizing Cream",
        origin="US",
        category="moisturizer",
        price="18.00",
        currency="USD",
        summary="Rich body and face cream with ceramides and hyaluronic acid for lasting hydration.",
        hero_ingredients="Ceramides, hyaluronic acid",
        rating=4.9,
        concerns=["dryness", "damaged-skin-barrier", "sensitivity"],
        ingredients=["ceramides", "hyaluronic-acid", "panthenol"],
        skin_types=["dry", "normal", "sensitive"],
        restrictions=["fragrance-free", "non-comedogenic"] ,
        product_url="https://www.cerave.com/skincare/moisturizers/moisturizing-cream",
        image="https://thmappbkk.blob.core.windows.net/boots/2025/10/1/9fb03389-51d7-46fa-8aa1-954bd57a5c28_large.jpg",
    ),
    ProductSeed(
        brand="CeraVe",
        name="PM Facial Moisturizing Lotion",
        origin="US",
        category="moisturizer",
        price="17.00",
        currency="USD",
        summary="Lightweight night moisturizer with niacinamide and ceramides to repair skin.",
        hero_ingredients="Ceramides, niacinamide",
        rating=4.7,
        concerns=["sensitivity", "dryness", "uneven-skin-texture"],
        ingredients=["ceramides", "niacinamide", "panthenol"],
        skin_types=["normal", "combination", "oily", "sensitive"],
        restrictions=["fragrance-free", "non-comedogenic"] ,
        product_url="https://www.cerave.com/skincare/moisturizers/pm-facial-moisturizing-lotion",
        image="https://media.allaboutyou.co.th/media/catalog/product/cache/68bd2c830b15d292727e06e369c4931c/a/e/ae789e54c835613253114275ece676bc76c7f370b11ed37b6c23066bf850d3af.jpeg",
    ),
    ProductSeed(
        brand="La Roche-Posay",
        name="Effaclar Duo (+) Acne Treatment",
        origin="FR",
        category="treatment",
        price="30.00",
        currency="USD",
        summary="Dual-action acne treatment that clears blemishes and fades marks.",
        hero_ingredients="Benzoyl peroxide, niacinamide",
        rating=4.5,
        concerns=["acne-breakouts", "blemishes", "large-pores"],
        ingredients=["salicylic-acid", "niacinamide", "panthenol"],
        skin_types=["oily", "combination"],
        restrictions=["oil-free", "non-comedogenic"] ,
        product_url="https://www.laroche-posay.us/acne/acne-spot-treatments/effaclar-dual-action-acne-treatment",
        image="https://www.laroche-posay.us/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-laroche-posay-master-catalog/default/dwa3f470a4/img/effaclarduoacnespottreatment/effaclar-duo-acne-spot-treatment-883140500759-1.jpg",
    ),
    ProductSeed(
        brand="La Roche-Posay",
        name="Toleriane Double Repair Moisturizer",
        origin="FR",
        category="moisturizer",
        price="22.00",
        currency="USD",
        summary="Daily moisturizer with ceramide-3 and prebiotic thermal water.",
        hero_ingredients="Ceramide-3, niacinamide",
        rating=4.7,
        concerns=["damaged-skin-barrier", "dryness", "sensitivity"],
        ingredients=["ceramides", "niacinamide", "panthenol"],
        skin_types=["normal", "dry", "sensitive"],
        restrictions=["fragrance-free", "oil-free"] ,
        product_url="https://www.laroche-posay.us/face-and-body-moisturizers/toleriane-double-repair-face-moisturizer",
        image="https://i5.walmartimages.com/seo/La-Roche-Posay-Toleriane-Double-Repair-Face-Moisturizer-SPF-30-3-38-fl-oz_ed9819a5-bb68-44b6-8979-4d29c35e85d1.a47bf56ba4960edbc866312dbe60a205.png",
    ),
    ProductSeed(
        brand="La Roche-Posay",
        name="Anthelios Melt-in Milk Sunscreen SPF 60",
        origin="FR",
        category="sunscreen",
        price="36.00",
        currency="USD",
        summary="Fast absorbing sunscreen providing broad spectrum protection and hydration.",
        hero_ingredients="Cell-Ox shield technology",
        rating=4.6,
        concerns=["sun-protection", "dryness", "sensitivity"],
        ingredients=["vitamin-e", "panthenol", "titanium-dioxide"],
        skin_types=["normal", "dry", "combination"],
        restrictions=["water-resistant"] ,
        product_url="https://www.laroche-posay.us/sunscreen/anthelios/anthelios-melt-in-milk-sunscreen-spf-60",
        image="https://www.laroche-posay.us/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-laroche-posay-master-catalog/default/dwe3151dc4/product/March%202023%20packshot%20updates/anthelios-melt-in-milk-body-sunscreen-883140500322-1.jpg",
    ),
    ProductSeed(
        brand="Neutrogena",
        name="Hydro Boost Water Gel",
        origin="US",
        category="moisturizer",
        price="24.00",
        currency="USD",
        summary="Refreshing gel moisturizer that instantly quenches dry skin.",
        hero_ingredients="Hyaluronic acid, glycerin",
        rating=4.6,
        concerns=["dehydrated-skin", "dryness", "dull-skin"],
        ingredients=["hyaluronic-acid", "panthenol", "squalane"],
        skin_types=["normal", "combination", "oily"],
        restrictions=["oil-free", "non-comedogenic"] ,
        product_url="https://www.neutrogena.com/products/skincare/hydro-boost-water-gel",
        image="https://img.drz.lazcdn.com/static/bd/p/56fff745e0f927c7e74fb9b03155c9c1.jpg_720x720q80.jpg",
    ),
    ProductSeed(
        brand="Neutrogena",
        name="Ultra Sheer Dry-Touch Sunscreen SPF 55",
        origin="US",
        category="sunscreen",
        price="11.00",
        currency="USD",
        summary="Fast-absorbing sunscreen with Dry-Touch technology for a matte finish.",
        hero_ingredients="Helioplex, vitamin E",
        rating=4.5,
        concerns=["sun-protection", "excess-oil", "hyperpigmentation"],
        ingredients=["vitamin-e", "titanium-dioxide", "panthenol"],
        skin_types=["oily", "combination", "normal"],
        restrictions=["water-resistant", "non-comedogenic"] ,
        product_url="https://www.neutrogena.com/products/sun/ultra-sheer-dry-touch-sunscreen-spf-55",
        image="https://images.ctfassets.net/bcjr30vxh6td/rsxMVyeMGbNsndAZQpHtP/06a1257abd4c07dd6fcb1976cb9f8c57/6868790_Carousel1.webp?fm=webp&w=3840",
    ),
    ProductSeed(
        brand="Kiehl's",
        name="Ultra Facial Cream",
        origin="US",
        category="moisturizer",
        price="38.00",
        currency="USD",
        summary="Daily lightweight moisturizer that replenishes skin for 24-hour hydration.",
        hero_ingredients="Squalane, glacial glycoprotein",
        rating=4.7,
        concerns=["dryness", "dehydrated-skin", "damaged-skin-barrier"],
        ingredients=["squalane", "hyaluronic-acid", "panthenol"],
        skin_types=["normal", "dry", "combination"],
        restrictions=[],
        product_url="https://www.kiehls.com/skincare/moisturizers/ultra-facial-cream",
        image="https://m.media-amazon.com/images/I/61271b8GniL._SL1500_.jpg",
    ),
    ProductSeed(
        brand="Kiehl's",
        name="Calendula Deep Cleansing Foaming Face Wash",
        origin="US",
        category="cleanser",
        price="36.00",
        currency="USD",
        summary="Gentle foaming cleanser with calendula to remove impurities without stripping.",
        hero_ingredients="Calendula extract, glycerin",
        rating=4.6,
        concerns=["excess-oil", "redness", "uneven-skin-texture"],
        ingredients=["calendula", "panthenol", "green-tea"],
        skin_types=["normal", "combination", "oily"],
        restrictions=[],
        product_url="https://www.kiehls.com/skincare/face-cleansers/calendula-deep-cleansing-foaming-face-wash",
        image="https://laskin.vn/wp-content/uploads/2022/10/8e2ac688f04924aa548c0a935c7a85e3.jpg",
    ),
    ProductSeed(
        brand="Kiehl's",
        name="Clearly Corrective Dark Spot Solution",
        origin="US",
        category="serum",
        price="62.00",
        currency="USD",
        summary="Brightening serum that visibly diminishes dark spots and discoloration.",
        hero_ingredients="Activated vitamin C, white birch",
        rating=4.6,
        concerns=["hyperpigmentation", "dull-skin", "uneven-skin-texture"],
        ingredients=["vitamin-c", "alpha-arbutin", "panthenol"],
        skin_types=["normal", "combination", "dry"],
        restrictions=[],
        product_url="https://www.kiehls.com/skincare/serums/clearly-corrective-dark-spot-solution",
        image="https://s3.konvy.com/static/team/2020/0316/15843400241106.jpg",
    ),
    ProductSeed(
        brand="Estée Lauder",
        name="Advanced Night Repair Synchronized Multi-Recovery Complex",
        origin="US",
        category="serum",
        price="110.00",
        currency="USD",
        summary="Iconic nighttime serum that reduces a wide range of aging signs.",
        hero_ingredients="Chronolux Power Signal Technology",
        rating=4.8,
        concerns=["fine-lines-wrinkles", "firmness", "dull-skin"],
        ingredients=["peptides", "fermented-yeast", "hyaluronic-acid"],
        skin_types=["normal", "dry", "combination"],
        restrictions=[],
        product_url="https://www.esteelauder.com/product/681/804/product-catalog/skincare",
        image="https://inwfile.com/s-dh/2i0cnn.jpg",
    ),
    ProductSeed(
        brand="Clinique",
        name="Moisture Surge 100H Auto-Replenishing Hydrator",
        origin="US",
        category="moisturizer",
        price="44.00",
        currency="USD",
        summary="Gel-cream moisturizer that penetrates deeply for 100 hours of hydration.",
        hero_ingredients="Aloe bio-ferment, hyaluronic acid",
        rating=4.7,
        concerns=["dehydrated-skin", "dull-skin", "dryness"],
        ingredients=["hyaluronic-acid", "fermented-yeast", "panthenol"],
        skin_types=["normal", "combination", "dry"],
        restrictions=["fragrance-free"] ,
        product_url="https://www.clinique.com/product/1573/101984/moisture-surge-100h",
        image="https://s3.konvy.com/static/team/2024/0219/17083273066790.jpg",
    ),
    ProductSeed(
        brand="Clinique",
        name="Take The Day Off Cleansing Balm",
        origin="US",
        category="balm",
        price="36.00",
        currency="USD",
        summary="Lightweight balm that transforms into oil to dissolve makeup.",
        hero_ingredients="Safflower seed oil, vitamin E",
        rating=4.8,
        concerns=["blackheads", "excess-oil", "uneven-skin-texture"],
        ingredients=["squalane", "vitamin-e", "panthenol"],
        skin_types=["normal", "dry", "combination", "oily"],
        restrictions=["fragrance-free"] ,
        product_url="https://www.clinique.com/product/1683/5135/skin-care",
        image="https://buybeautique.com/cdn/shop/files/s886267-main-zoom.webp?v=1699095110",
    ),
    ProductSeed(
        brand="Drunk Elephant",
        name="C-Firma Fresh Day Serum",
        origin="US",
        category="serum",
        price="78.00",
        currency="USD",
        summary="Potent 15% vitamin C day serum that firms and brightens the skin.",
        hero_ingredients="L-ascorbic acid, ferulic acid",
        rating=4.6,
        concerns=["hyperpigmentation", "dull-skin", "fine-lines-wrinkles"],
        ingredients=["vitamin-c", "vitamin-e", "fermented-yeast"],
        skin_types=["normal", "combination", "dry"],
        restrictions=["vegan", "cruelty-free", "fragrance-free"] ,
        product_url="https://www.drunkelephant.com/products/c-firma-fresh-day-serum",
        image="https://mcgrocer.com/cdn/shop/files/drunk-elephant-c-firma-fresh-day-serum-40509612065006.jpg?v=1739327362",
    ),
    ProductSeed(
        brand="Drunk Elephant",
        name="T.L.C. Framboos Glycolic Night Serum",
        origin="US",
        category="serum",
        price="90.00",
        currency="USD",
        summary="Night serum with AHA/BHA blend to refine texture and clarity.",
        hero_ingredients="Glycolic acid, salicylic acid",
        rating=4.7,
        concerns=["uneven-skin-texture", "dull-skin", "fine-lines-wrinkles"],
        ingredients=["glycolic-acid", "lactic-acid", "salicylic-acid"],
        skin_types=["normal", "combination", "oily"],
        restrictions=["vegan", "cruelty-free", "fragrance-free"] ,
        product_url="https://www.drunkelephant.com/products/t-l-c-framboos",
        image="https://img.kingpowerclick.com/cdn-cgi/image/format=auto/kingpower-com/image/upload/w_640/prod/959209-L1.jpg",
    ),
    ProductSeed(
        brand="Sunday Riley",
        name="Good Genes All-In-One Lactic Acid Treatment",
        origin="US",
        category="treatment",
        price="85.00",
        currency="USD",
        summary="Lactic acid treatment that exfoliates, brightens, and plumps skin.",
        hero_ingredients="Purified lactic acid, licorice",
        rating=4.6,
        concerns=["dull-skin", "fine-lines-wrinkles", "uneven-skin-texture"],
        ingredients=["lactic-acid", "licorice-root", "squalane"],
        skin_types=["normal", "dry", "combination"],
        restrictions=["cruelty-free"] ,
        product_url="https://sundayriley.com/products/good-genes",
        image="https://www.sephora.com/productimages/sku/s2715332-main-zoom.jpg?pb=allure-2023-bestofbeauty-badge",
    ),
    ProductSeed(
        brand="Tatcha",
        name="The Water Cream",
        origin="US",
        category="moisturizer",
        price="70.00",
        currency="USD",
        summary="Oil-free gel-cream that provides balanced hydration and refines pores.",
        hero_ingredients="Hadasei-3 complex, Japanese wild rose",
        rating=4.7,
        concerns=["large-pores", "excess-oil", "dull-skin"],
        ingredients=["green-tea", "fermented-yeast", "rice-extract"],
        skin_types=["normal", "oily", "combination"],
        restrictions=["cruelty-free"] ,
        product_url="https://www.tatcha.com/product/the-water-cream",
        image="https://www.tatcha.com/on/demandware.static/-/Sites-master_catalog_tatcha/default/dw4ca30f17/images/product-images/moisturizers/WaterCream-1-FS-new-main-image.jpg",
    ),
    ProductSeed(
        brand="Tatcha",
        name="The Dewy Skin Cream",
        origin="US",
        category="moisturizer",
        price="70.00",
        currency="USD",
        summary="Rich cream that imparts plump hydration and youthful glow.",
        hero_ingredients="Okinawa algae blend, hyaluronic acid",
        rating=4.8,
        concerns=["dryness", "dehydrated-skin", "firmness"],
        ingredients=["hyaluronic-acid", "squalane", "fermented-yeast"],
        skin_types=["dry", "normal", "combination"],
        restrictions=["cruelty-free"] ,
        product_url="https://www.tatcha.com/product/the-dewy-skin-cream",
        image="https://www.tatcha.co.uk/cdn/shop/files/TAT24_OCT_SI_PP_Tatcha-UK_DSC_JUMBOS-HERO_CLOSED-JAR_750x750_MR_2048x.jpg?v=1757433659",
    ),
    ProductSeed(
        brand="Glow Recipe",
        name="Watermelon Glow Niacinamide Dew Drops",
        origin="US",
        category="serum",
        price="34.00",
        currency="USD",
        summary="Highlighting skincare-serum hybrid that visibly reduces hyperpigmentation.",
        hero_ingredients="Niacinamide, watermelon",
        rating=4.6,
        concerns=["dull-skin", "hyperpigmentation", "large-pores"],
        ingredients=["niacinamide", "hyaluronic-acid", "panthenol"],
        skin_types=["normal", "combination", "dry"],
        restrictions=["cruelty-free", "vegan"] ,
        product_url="https://www.glowrecipe.com/products/watermelon-glow-niacinamide-dew-drops",
        image="https://www.cultbeauty.com/images?url=https://static.thcdn.com/productimg/original/13910972-1884983758574423.jpg&format=webp&auto=avif&width=985&height=985&fit=cover",
    ),
    ProductSeed(
        brand="Glow Recipe",
        name="Avocado Melt Retinol Sleeping Mask",
        origin="US",
        category="mask",
        price="49.00",
        currency="USD",
        summary="Nourishing overnight mask with encapsulated retinol and avocado.",
        hero_ingredients="Encapsulated retinol, avocado",
        rating=4.5,
        concerns=["fine-lines-wrinkles", "dull-skin", "uneven-skin-texture"],
        ingredients=["retinol", "squalane", "niacinamide"],
        skin_types=["normal", "dry", "combination"],
        restrictions=["cruelty-free"] ,
        product_url="https://www.glowrecipe.com/products/avocado-melt-retinol-sleeping-mask",
        image="https://i1.wp.com/blog.glowrecipe.com/wp-content/uploads/2019/08/Glow-Recipe-Avocado-Melt-Retinol-Sleeping-Mask-Pack-Shot.jpg?fit=1024%2C1024&ssl=1",
    ),
    ProductSeed(
        brand="First Aid Beauty",
        name="Ultra Repair Cream Intense Hydration",
        origin="US",
        category="moisturizer",
        price="38.00",
        currency="USD",
        summary="Head-to-toe moisturizer that provides instant relief for dry, distressed skin.",
        hero_ingredients="Colloidal oatmeal, shea butter",
        rating=4.8,
        concerns=["dryness", "damaged-skin-barrier", "sensitivity"],
        ingredients=["oatmeal", "shea-butter", "ceramides"],
        skin_types=["dry", "normal", "sensitive"],
        restrictions=["fragrance-free"] ,
        product_url="https://www.firstaidbeauty.com/product/ultra-repair-cream",
        image="https://www.firstaidbeauty.com/cdn/shop/files/UltraRepairCream_6oz_Lead_2000x2000_d8b2f943-720b-438d-bf22-b3a8cd497298.jpg?v=1716235447&width=1946",
    ),
    ProductSeed(
        brand="First Aid Beauty",
        name="Facial Radiance Pads",
        origin="US",
        category="treatment",
        price="36.00",
        currency="USD",
        summary="Daily exfoliating pads to brighten and tone with AHA/BHA blend.",
        hero_ingredients="Lactic acid, glycolic acid",
        rating=4.6,
        concerns=["dull-skin", "uneven-skin-texture", "dark-circles"],
        ingredients=["lactic-acid", "glycolic-acid", "licorice-root"],
        skin_types=["normal", "combination", "oily"],
        restrictions=["cruelty-free"] ,
        product_url="https://www.firstaidbeauty.com/product/facial-radiance-pads",
        image="https://www.firstaidbeauty.com/cdn/shop/files/Facial_Radiance_Pads_60ct_d0d80d4f-767c-41e8-8dfe-50bb2442c147.jpg?v=1717166845&width=1946",
    ),
    ProductSeed(
        brand="Biossance",
        name="Squalane + Vitamin C Rose Oil",
        origin="US",
        category="oil",
        price="74.00",
        currency="USD",
        summary="Luxurious face oil that brightens and firms with vitamin C and squalane.",
        hero_ingredients="THD vitamin C, squalane",
        rating=4.7,
        concerns=["dull-skin", "fine-lines-wrinkles", "hyperpigmentation"],
        ingredients=["squalane", "vitamin-c", "vitamin-e"],
        skin_types=["dry", "normal", "combination"],
        restrictions=["vegan", "cruelty-free"] ,
        product_url="https://biossance.com/products/squalane-vitamin-c-rose-oil",
        image="https://static.thcdn.com/images/large/original//productimg/1600/1600/12766621-9424897139105061.jpg",
    ),
    ProductSeed(
        brand="Ole Henriksen",
        name="Banana Bright Eye Crème",
        origin="US",
        category="treatment",
        price="42.00",
        currency="USD",
        summary="Vitamin C-rich eye crème that brightens, firms, and color corrects.",
        hero_ingredients="Vitamin C, collagen",
        rating=4.5,
        concerns=["dark-circles", "puffiness", "fine-lines-wrinkles"],
        ingredients=["vitamin-c", "peptides", "vitamin-e"],
        skin_types=["normal", "dry", "combination"],
        restrictions=["cruelty-free"] ,
        product_url="https://www.olehenriksen.com/products/banana-bright-eye-creme",
        image="https://d3pllp7nz3wmw5.cloudfront.net/product_images/26941513001-1_FULL.jpg",
    ),
    ProductSeed(
        brand="Murad",
        name="Rapid Dark Spot Correcting Serum",
        origin="US",
        category="serum",
        price="72.00",
        currency="USD",
        summary="Dark spot serum featuring resorcinol and tranexamic acid to reduce discoloration.",
        hero_ingredients="Resorcinol, tranexamic acid",
        rating=4.6,
        concerns=["hyperpigmentation", "dull-skin", "uneven-skin-texture"],
        ingredients=["tranexamic-acid", "vitamin-c", "niacinamide"],
        skin_types=["normal", "combination", "dry"],
        restrictions=[],
        product_url="https://www.murad.com/product/rapid-dark-spot-correcting-serum/",
        image="https://www.konvy.com/static/team/2025/0213/17394306659140_600x600.jpg",
    ),
    ProductSeed(
        brand="Peter Thomas Roth",
        name="Water Drench Hyaluronic Cloud Cream",
        origin="US",
        category="moisturizer",
        price="52.00",
        currency="USD",
        summary="Weightless cream with 30% hyaluronic acid complex for intense hydration.",
        hero_ingredients="Hyaluronic acid, ceramides",
        rating=4.7,
        concerns=["dehydrated-skin", "dryness", "dull-skin"],
        ingredients=["hyaluronic-acid", "ceramides", "squalane"],
        skin_types=["normal", "combination", "dry"],
        restrictions=[],
        product_url="https://www.peterthomasroth.com/product/water-drench-hyaluronic-cloud-cream",
        image="https://media.farmaciatei.ro/gallery/68924/crema-pentru-fata-water-drench-hyaluronic-cloud-cream-hydrating-moisturizer-20-ml-peter-thomas-roth-8601.jpg",
    ),
    ProductSeed(
        brand="Youth To The People",
        name="Superfood Antioxidant Cleanser",
        origin="US",
        category="cleanser",
        price="39.00",
        currency="USD",
        summary="Daily green juice cleanser with kale, spinach, and vitamins.",
        hero_ingredients="Kale, spinach, green tea",
        rating=4.7,
        concerns=["excess-oil", "dull-skin", "uneven-skin-texture"],
        ingredients=["green-tea", "panthenol", "vitamin-e"],
        skin_types=["normal", "combination", "oily"],
        restrictions=["vegan", "cruelty-free"] ,
        product_url="https://www.youthtothepeople.com/products/superfood-cleanser",
        image="https://www.youthtothepeople.com/dw/image/v2/AAFM_PRD/on/demandware.static/-/Sites-yttp-master-catalog/default/dw92070e07/products/YTTP-10100/09-2024/YTTP_Website_Cleanser_Frontal_Allure_Badge_3.jpg",
    ),
    ProductSeed(
        brand="Youth To The People",
        name="Superberry Hydrate + Glow Dream Mask",
        origin="US",
        category="mask",
        price="48.00",
        currency="USD",
        summary="Overnight mask with antioxidant-packed superberries and squalane.",
        hero_ingredients="Maqui, vitamin C",
        rating=4.6,
        concerns=["dull-skin", "dryness", "dehydrated-skin"],
        ingredients=["vitamin-c", "squalane", "panthenol"],
        skin_types=["normal", "dry", "combination"],
        restrictions=["vegan", "cruelty-free"] ,
        product_url="https://www.youthtothepeople.com/products/superberry-dream-mask",
        image="https://www.sephora.com/productimages/sku/s2379444-main-zoom.jpg?imwidth=315",
    ),
    ProductSeed(
        brand="Tula",
        name="Cult Classic Purifying Face Cleanser",
        origin="US",
        category="cleanser",
        price="34.00",
        currency="USD",
        summary="Probiotic gel cleanser that removes impurities while maintaining balance.",
        hero_ingredients="Probiotics, turmeric",
        rating=4.6,
        concerns=["dull-skin", "uneven-skin-texture", "acne-breakouts"],
        ingredients=["fermented-yeast", "turmeric", "panthenol"],
        skin_types=["normal", "combination", "oily"],
        restrictions=["cruelty-free"] ,
        product_url="https://www.tula.com/products/cult-classic-cleanser",
        image="https://www.sephora.com/productimages/sku/s2500684-main-zoom.jpg?imwidth=315",
    ),
    ProductSeed(
        brand="Dr. Dennis Gross",
        name="Alpha Beta Universal Daily Peel",
        origin="US",
        category="treatment",
        price="88.00",
        currency="USD",
        summary="Two-step daily peel to improve tone, texture, and radiance.",
        hero_ingredients="Alpha and beta hydroxy acids",
        rating=4.7,
        concerns=["dull-skin", "fine-lines-wrinkles", "uneven-skin-texture"],
        ingredients=["glycolic-acid", "lactic-acid", "salicylic-acid"],
        skin_types=["normal", "combination", "oily"],
        restrictions=["cruelty-free"] ,
        product_url="https://drdennisgross.com/products/alpha-beta-universal-daily-peel",
        image="https://www.sephora.com/productimages/sku/s1722487-main-zoom.jpg",
    ),
    ProductSeed(
        brand="SkinCeuticals",
        name="C E Ferulic",
        origin="US",
        category="serum",
        price="182.00",
        currency="USD",
        summary="Vitamin C serum with ferulic acid to deliver advanced environmental protection.",
        hero_ingredients="15% vitamin C, vitamin E, ferulic acid",
        rating=4.8,
        concerns=["fine-lines-wrinkles", "firmness", "hyperpigmentation"],
        ingredients=["vitamin-c", "vitamin-e", "fermented-yeast"],
        skin_types=["normal", "dry", "combination"],
        restrictions=[],
        product_url="https://www.skinceuticals.com/c-e-ferulic",
        image="https://www.lmching.com/cdn/shop/files/D_anm_i-72_bc9cded0-3df6-444b-8838-d90ebb7644ec_540x.jpg?v=1722253755",
    ),
    ProductSeed(
        brand="Differin",
        name="Adapalene Gel 0.1% Acne Treatment",
        origin="US",
        category="treatment",
        price="13.00",
        currency="USD",
        summary="Retinoid gel that clears and prevents acne with adapalene.",
        hero_ingredients="Adapalene",
        rating=4.6,
        concerns=["acne-breakouts", "blemishes", "uneven-skin-texture"],
        ingredients=["retinol", "panthenol", "niacinamide"],
        skin_types=["oily", "combination", "normal"],
        restrictions=["oil-free"] ,
        product_url="https://www.differin.com/products/adapalene-gel-0-1-acne-treatment",
        image="https://cloudinary.images-iherb.com/image/upload/f_auto,q_auto:eco/images/dif/dif92030/l/41.jpg",
    ),
    ProductSeed(
        brand="Olay",
        name="Regenerist Micro-Sculpting Cream",
        origin="US",
        category="moisturizer",
        price="32.00",
        currency="USD",
        summary="Anti-aging moisturizer formulated to visibly plump and smooth skin.",
        hero_ingredients="Niacinamide, peptides",
        rating=4.7,
        concerns=["firmness", "fine-lines-wrinkles", "dryness"],
        ingredients=["niacinamide", "peptides", "panthenol"],
        skin_types=["normal", "dry", "combination"],
        restrictions=[],
        product_url="https://www.olay.com/regenerist-micro-sculpting-cream",
        image="https://s3.konvy.com/static/team/2018/0222/15192962407073.jpg",
    ),
    ProductSeed(
        brand="Aveeno",
        name="Calm + Restore Oat Gel Moisturizer",
        origin="US",
        category="moisturizer",
        price="26.00",
        currency="USD",
        summary="Gel moisturizer designed for sensitive skin with soothing oat and feverfew.",
        hero_ingredients="Colloidal oatmeal, feverfew",
        rating=4.6,
        concerns=["sensitivity", "redness", "dryness"],
        ingredients=["oatmeal", "panthenol", "squalane"],
        skin_types=["sensitive", "normal", "combination"],
        restrictions=["fragrance-free"] ,
        product_url="https://www.aveeno.com/products/calm-restore-oat-gel-moisturizer",
        image="https://img.lazcdn.com/g/p/d8fde17cc0a6d270b95c7df82ac442b4.jpg_720x720q80.jpg",
    ),
    ProductSeed(
        brand="Eucerin",
        name="Advanced Repair Cream",
        origin="DE",
        category="moisturizer",
        price="15.00",
        currency="USD",
        summary="Rich body cream providing 48-hour moisture and strengthening the barrier.",
        hero_ingredients="Ceramides, urea",
        rating=4.6,
        concerns=["dryness", "damaged-skin-barrier", "uneven-skin-texture"],
        ingredients=["ceramides", "shea-butter", "panthenol"],
        skin_types=["dry", "normal"],
        restrictions=[],
        product_url="https://www.eucerinus.com/products/advanced-repair-cream",
        image="https://beautymarkedgh.com/cdn/shop/products/eucerin_grande.png?v=1627510533",
    ),
    ProductSeed(
        brand="Bioderma",
        name="Sensibio H2O Micellar Water",
        origin="FR",
        category="cleanser",
        price="15.00",
        currency="USD",
        summary="Iconic micellar water that gently removes makeup while respecting sensitive skin.",
        hero_ingredients="Micelles, cucumber extract",
        rating=4.8,
        concerns=["sensitivity", "redness", "dryness"],
        ingredients=["green-tea", "panthenol", "chamomile"],
        skin_types=["sensitive", "normal", "combination"],
        restrictions=["fragrance-free"] ,
        product_url="https://www.bioderma.us/our-products/sensibio/h2o",
        image="https://www.bioderma.co.th/sites/th/files/styles/fancybox_2000_2000/public/products/%7B157387%7D_%7B%7D_%7B28703X%7D.jpg?itok=ZksLdNWn",
    ),
    ProductSeed(
        brand="Vichy",
        name="Mineral 89 Hyaluronic Acid Serum",
        origin="FR",
        category="serum",
        price="29.50",
        currency="USD",
        summary="Daily booster combining 89% mineralizing water and hyaluronic acid.",
        hero_ingredients="Vichy volcanic water, hyaluronic acid",
        rating=4.7,
        concerns=["dehydrated-skin", "dull-skin", "damaged-skin-barrier"],
        ingredients=["hyaluronic-acid", "panthenol", "squalane"],
        skin_types=["normal", "dry", "combination"],
        restrictions=["oil-free", "alcohol-free"] ,
        product_url="https://www.vichyusa.com/mineral-89-3337875583626.html",
        image="https://www.vichyusa.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-vichy-master-catalog/default/dwfc8759c1/product/Mineral89/NEW-%20Vichy-Mineral-89-Hyaluronic-Acid-Face-Serum-50-ml-3337875543248-PDP-1%20(2).jpg",
    ),
    ProductSeed(
        brand="Pixi",
        name="Glow Tonic",
        origin="UK",
        category="toner",
        price="18.00",
        currency="USD",
        summary="Radiance-enhancing toner with 5% glycolic acid to exfoliate and brighten.",
        hero_ingredients="Glycolic acid, ginseng",
        rating=4.6,
        concerns=["dull-skin", "uneven-skin-texture", "large-pores"],
        ingredients=["glycolic-acid", "licorice-root", "green-tea"],
        skin_types=["normal", "combination", "oily"],
        restrictions=["cruelty-free"] ,
        product_url="https://www.pixibeauty.com/products/glow-tonic",
        image="https://mcgrocer.com/cdn/shop/files/pixi-glow-tonic-250ml-40437632270574.jpg?v=1745459136",
    ),
]

PRODUCTS: list[ProductSeed] = (
    KOREAN_PRODUCTS
    + JAPANESE_PRODUCTS
    + THAI_PRODUCTS
    + GLOBAL_PRODUCTS
)


def _ensure_reference_data():
    concern_map = {}
    for key, name in CONCERNS:
        concern, _ = SkinConcern.objects.update_or_create(
            key=key,
            defaults={"name": name},
        )
        concern_map[key] = concern

    skin_type_map = {}
    for key, name in SKIN_TYPES:
        skin_type, _ = SkinTypeTag.objects.update_or_create(
            key=key,
            defaults={"name": name},
        )
        skin_type_map[key] = skin_type

    restriction_map = {}
    for key, name in RESTRICTIONS:
        restriction, _ = RestrictionTag.objects.update_or_create(
            key=key,
            defaults={"name": name},
        )
        restriction_map[key] = restriction

    ingredient_map: dict[str, Ingredient] = {}
    for key, common_name, benefits in INGREDIENTS:
        possible_keys = {key}
        if "-" in key:
            possible_keys.add(key.replace("-", "_"))
        if "_" in key:
            possible_keys.add(key.replace("_", "-"))
        ingredient: Ingredient | None = None
        for candidate in possible_keys:
            ingredient = Ingredient.objects.filter(key=candidate).first()
            if ingredient:
                break
        if ingredient:
            updates = {}
            if ingredient.common_name != common_name:
                updates["common_name"] = common_name
            if ingredient.benefits != benefits:
                updates["benefits"] = benefits
            notes = INGREDIENT_NOTES.get(key, {})
            for field, value in notes.items():
                if getattr(ingredient, field) != value:
                    updates[field] = value
            if updates:
                Ingredient.objects.filter(pk=ingredient.pk).update(**updates)
                ingredient.refresh_from_db(fields=list(updates.keys()))
        else:
            notes = INGREDIENT_NOTES.get(key, {})
            ingredient = Ingredient.objects.create(
                key=key,
                common_name=common_name,
                benefits=benefits,
                helps_with=notes.get("helps_with", ""),
                avoid_with=notes.get("avoid_with", ""),
                side_effects=notes.get("side_effects", ""),
            )
        ingredient_map[key] = ingredient

    return concern_map, skin_type_map, restriction_map, ingredient_map


def _product_defaults(seed: ProductSeed) -> dict:
    return {
        "brand": seed.brand,
        "name": seed.name,
        "origin_country": seed.origin,
        "category": seed.category,
        "summary": seed.summary,
        "hero_ingredients": seed.hero_ingredients,
        "price": Decimal(seed.price),
        "currency": seed.currency,
        "rating": seed.rating,
        "product_url": seed.product_url or "",
        "image": seed.image or "",
        "is_active": True,
    }


def _set_product_relations(
    product: Product,
    seed: ProductSeed,
    concern_map: dict[str, SkinConcern],
    skin_type_map: dict[str, SkinTypeTag],
    restriction_map: dict[str, RestrictionTag],
    ingredient_map: dict[str, Ingredient],
) -> None:
    ProductConcern.objects.filter(product=product).delete()
    for index, concern_key in enumerate(seed.concerns):
        concern = concern_map[concern_key]
        ProductConcern.objects.create(
            product=product,
            concern=concern,
            weight=90 - index * 10,
        )

    ProductIngredient.objects.filter(product=product).delete()
    for order, ingredient_key in enumerate(seed.ingredients):
        ingredient = ingredient_map[ingredient_key]
        ProductIngredient.objects.create(
            product=product,
            ingredient=ingredient,
            order=order,
            highlight=order < 3,
        )

    ProductSkinType.objects.filter(product=product).delete()
    for skin_type_key in seed.skin_types:
        skin_type = skin_type_map[skin_type_key]
        ProductSkinType.objects.create(
            product=product,
            skin_type=skin_type,
            compatibility=85,
        )

    restriction_objects = [restriction_map[key] for key in seed.restrictions]
    product.restrictions.set(restriction_objects)


class Command(BaseCommand):
    help = "Load a curated catalog of skincare products into the database."

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Delete existing catalog entries before loading sample data.",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        from django.apps import apps

        if options["reset"]:
            self.stdout.write("Clearing existing catalog data...")
            ProductSkinType.objects.all().delete()
            ProductIngredient.objects.all().delete()
            ProductConcern.objects.all().delete()
            Product.objects.all().delete()

        concern_map, skin_type_map, restriction_map, ingredient_map = _ensure_reference_data()

        if not PRODUCTS:
            raise RuntimeError("PRODUCTS dataset is empty; populate it before running the command.")

        created, updated = 0, 0
        for seed in PRODUCTS:
            slug = slugify(f"{seed.brand} {seed.name}")
            defaults = _product_defaults(seed)
            product, is_created = Product.objects.update_or_create(
                slug=slug,
                defaults=defaults,
            )
            _set_product_relations(
                product,
                seed,
                concern_map,
                skin_type_map,
                restriction_map,
                ingredient_map,
            )
            if is_created:
                created += 1
            else:
                updated += 1

        self.stdout.write(self.style.SUCCESS(
            f"Catalog load complete: {created} created, {updated} updated."
        ))
