"""
Django settings for apidemo project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

import os
import dj_database_url
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Utility helpers
def env_bool(name: str, default: bool = False) -> bool:
    return os.getenv(name, str(default)).lower() in ("1", "true", "yes", "on")

def env_csv(name: str, default: str = "") -> list[str]:
    raw = os.getenv(name, default)
    return [item.strip().strip('"').strip("'") for item in raw.split(",") if item.strip()]

def append_unique(values: list[str], value: str | None) -> None:
    if value and value not in values:
        values.append(value)

# SECURITY WARNING: keep the secret key used in production secret
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-only-unsafe")

# SECURITY WARNING: don't run with debug turned on in production
DEBUG = os.environ.get("DJANGO_DEBUG", "False") == "True"

ALLOWED_HOSTS = env_csv("ALLOWED_HOSTS", "localhost,127.0.0.1,backend")
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["*"]

VERCEL_PROD_DOMAIN = os.getenv("VERCEL_PROD_DOMAIN", "").strip()
if VERCEL_PROD_DOMAIN:
    append_unique(ALLOWED_HOSTS, VERCEL_PROD_DOMAIN)
    append_unique(ALLOWED_HOSTS, f".{VERCEL_PROD_DOMAIN}")  # support subdomains

# CSRF / CORS
default_frontend_origins = [
    os.getenv("FRONTEND_ORIGIN", "http://localhost:3000"),
    "http://localhost:3000",
    "http://frontend:3000",  # Docker service name
]

CORS_ALLOWED_ORIGINS = env_csv(
    "CORS_ALLOWED_ORIGINS",
    ",".join(default_frontend_origins),
)
CORS_ALLOWED_ORIGINS = list(dict.fromkeys([origin for origin in CORS_ALLOWED_ORIGINS if origin]))
if VERCEL_PROD_DOMAIN:
    append_unique(CORS_ALLOWED_ORIGINS, f"https://{VERCEL_PROD_DOMAIN}")

CORS_ALLOWED_ORIGIN_REGEXES = env_csv(
    "CORS_ALLOWED_ORIGIN_REGEXES",
    r"^https://.*-vercel\.app$",
)
CORS_ALLOW_CREDENTIALS = True

default_csrf_origins = list(CORS_ALLOWED_ORIGINS)
if VERCEL_PROD_DOMAIN:
    append_unique(default_csrf_origins, f"https://{VERCEL_PROD_DOMAIN}")
append_unique(default_csrf_origins, "https://*.vercel.app")

CSRF_TRUSTED_ORIGINS = env_csv(
    "CSRF_TRUSTED_ORIGINS",
    ",".join(default_csrf_origins),
)
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys([origin for origin in CSRF_TRUSTED_ORIGINS if origin]))

_raw_google_ids = env_csv("GOOGLE_OAUTH_CLIENT_IDS", os.getenv("GOOGLE_OAUTH_CLIENT_ID", ""))
GOOGLE_OAUTH_CLIENT_IDS = [cid for cid in _raw_google_ids if cid]
GOOGLE_OAUTH_CLIENT_ID = GOOGLE_OAUTH_CLIENT_IDS[0] if GOOGLE_OAUTH_CLIENT_IDS else ""
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET", os.getenv("GOOGLE_CLIENT_SECRET", ""))
GOOGLE_OAUTH_REDIRECT_URI = os.getenv(
    "GOOGLE_OAUTH_REDIRECT_URI",
    os.getenv("GOOGLE_REDIRECT_URI", "http://localhost:8000/api/auth/google/callback"),
)
FRONTEND_LOGIN_REDIRECT_URL = os.getenv(
    "FRONTEND_LOGIN_REDIRECT_URL",
    "http://localhost:3000/account" 
)


# Application definition
INSTALLED_APPS = [
    'quiz',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",

    # 3rd-party
    "corsheaders",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",

    # Your apps
    "core.apps.CoreConfig",
]
SITE_ID = 1

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",          
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "apidemo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "apidemo.wsgi.application"

# Database
conn_max_age = int(os.getenv("DB_CONN_MAX_AGE", "600"))
ssl_require = env_bool("DB_SSL_REQUIRE", False)

default_db_url = os.getenv("DATABASE_URL")
if not default_db_url:
    default_db_url = (
        "postgresql://"
        f"{os.getenv('POSTGRES_USER', 'skinmatch_user')}:"
        f"{os.getenv('POSTGRES_PASSWORD', '')}"
        f"@{os.getenv('POSTGRES_HOST', '127.0.0.1')}:"
        f"{os.getenv('POSTGRES_PORT', '5432')}/"
        f"{os.getenv('POSTGRES_DB', os.getenv('DB_NAME', 'skinmatch_db'))}"
    )

DATABASES = {
    "default": dj_database_url.config(
        default=default_db_url,
        conn_max_age=conn_max_age,
        ssl_require=ssl_require,
    )
}

DATABASES["default"]["CONN_HEALTH_CHECKS"] = True

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,
        },
    },
    {
        "NAME": "core.password_validators.ComplexityPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = os.getenv("TIME_ZONE", "Asia/Bangkok")
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# Use this only if you have your own assets in a project /static folder
# STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# WhiteNoise staticfiles storage (prod only)
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Quiz configuration
QUIZ_REQUIRE_AUTH_FOR_PRODUCTS = False
QUIZ_AUTO_SEED_SAMPLE = env_bool("QUIZ_AUTO_SEED_SAMPLE", DEBUG)

# Email
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "SkinMatch <no-reply@skinmatch.local>")
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)

if EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend":
    EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
    EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
    EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", False)
    EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL", False)
    EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "0")) or None

# --- JWT config ---
from datetime import timedelta

# Signing key (use a dedicated secret in prod)
JWT_SECRET_KEY = os.getenv("JWT_SECRET_KEY", SECRET_KEY)

# Algorithm to sign tokens
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")

# Token lifetimes
JWT_ACCESS_TTL = timedelta(minutes=int(os.getenv("JWT_ACCESS_TTL_MIN", "15")))
JWT_REFRESH_TTL = timedelta(days=int(os.getenv("JWT_REFRESH_TTL_DAYS", "7")))

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend"
)

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

SITE_ID = int(os.getenv("SITE_ID", "1"))
ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = os.getenv("ACCOUNT_EMAIL_VERIFICATION", "optional")
ACCOUNT_PRESERVE_USERNAME_CASING = False
ACCOUNT_RATE_LIMITS = {
    "login_failed": os.getenv("ACCOUNT_RATE_LIMIT_LOGIN_FAILED", "5/5m"),
}
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": GOOGLE_OAUTH_CLIENT_ID,
            "secret": GOOGLE_OAUTH_CLIENT_SECRET,
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"prompt": "select_account"},
    }
}

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'quiz.ai': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'quiz': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
