# Generated by Django 5.2.6 on 2025-10-02 16:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('key', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=120, unique=True)),
                ('inci_name', models.CharField(blank=True, max_length=200)),
                ('benefits', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['common_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('brand', models.CharField(db_index=True, max_length=120)),
                ('origin_country', models.CharField(choices=[('KR', 'South Korea'), ('JP', 'Japan'), ('US', 'United States'), ('FR', 'France'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('OT', 'Other')], max_length=4)),
                ('category', models.CharField(choices=[('cleanser', 'Cleanser'), ('toner', 'Toner'), ('essence', 'Essence'), ('serum', 'Serum'), ('moisturizer', 'Moisturizer'), ('mask', 'Mask'), ('sunscreen', 'Sunscreen'), ('treatment', 'Treatment'), ('oil', 'Oil'), ('mist', 'Mist'), ('balm', 'Balm'), ('other', 'Other')], max_length=30)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('hero_ingredients', models.CharField(blank=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('KRW', 'KRW'), ('JPY', 'JPY'), ('EUR', 'EUR')], default='USD', max_length=3)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('product_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestrictionTag',
            fields=[
                ('key', models.SlugField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkinConcern',
            fields=[
                ('key', models.SlugField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkinTypeTag',
            fields=[
                ('key', models.SlugField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='matchpick',
            options={'ordering': ['session', 'rank']},
        ),
        migrations.RemoveField(
            model_name='matchpick',
            name='product_id',
        ),
        migrations.AddField(
            model_name='matchpick',
            name='brand',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='matchpick',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='matchpick',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='matchpick',
            name='product_slug',
            field=models.SlugField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='matchpick',
            name='rationale',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='matchpick',
            name='category',
            field=models.CharField(default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='matchpick',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='matchpick',
            name='product_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='matchpick',
            name='score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='matchpick',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_picks', to='quiz.product'),
        ),
        migrations.CreateModel(
            name='ProductIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('highlight', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.product')),
            ],
            options={
                'ordering': ['order', 'ingredient__common_name'],
                'unique_together': {('product', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='products', through='quiz.ProductIngredient', to='quiz.ingredient'),
        ),
        migrations.AddField(
            model_name='product',
            name='restrictions',
            field=models.ManyToManyField(blank=True, related_name='products', to='quiz.restrictiontag'),
        ),
        migrations.CreateModel(
            name='ProductConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField(default=60)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.product')),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.skinconcern')),
            ],
            options={
                'unique_together': {('product', 'concern')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='concerns',
            field=models.ManyToManyField(blank=True, related_name='products', through='quiz.ProductConcern', to='quiz.skinconcern'),
        ),
        migrations.CreateModel(
            name='ProductSkinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility', models.PositiveSmallIntegerField(default=80)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.product')),
                ('skin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.skintypetag')),
            ],
            options={
                'unique_together': {('product', 'skin_type')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='skin_types',
            field=models.ManyToManyField(blank=True, related_name='products', through='quiz.ProductSkinType', to='quiz.skintypetag'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='quiz_produc_categor_b3bab9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'is_active'], name='quiz_produc_brand_04b4e9_idx'),
        ),
    ]
