# Generated by Django 5.2.7 on 2025-10-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizfeedback'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quizfeedback',
            new_name='quiz_quizfe_created_ca7e51_idx',
            old_name='quiz_feed_created_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('KRW', 'KRW'), ('JPY', 'JPY'), ('EUR', 'EUR'), ('THB', 'THB')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_country',
            field=models.CharField(choices=[('KR', 'South Korea'), ('JP', 'Japan'), ('US', 'United States'), ('FR', 'France'), ('GB', 'United Kingdom'), ('CA', 'Canada'), ('TH', 'Thailand'), ('CH', 'China'), ('OT', 'Other')], max_length=4),
        ),
    ]
