# Generated by Django 5.2.6 on 2025-10-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_productreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productreview',
            new_name='quiz_produc_product_791a3e_idx',
            old_name='quiz_produc_product_2fbf41_idx',
        ),
        migrations.RenameIndex(
            model_name='productreview',
            new_name='quiz_produc_user_id_fe16ce_idx',
            old_name='quiz_produc_user_cre_1a6c5a_idx',
        ),
    ]
