# Generated by Django 5.2.7 on 2025-11-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_force_text_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Optional EAN/UPC barcode identifier', max_length=50, null=True, unique=True),
        ),
    ]
