# Generated by Django 5.2.7 on 2025-11-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_quizfeedback_rating'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quizfeedback',
            new_name='quiz_quizfe_rating_ee2040_idx',
            old_name='quiz_quizfeed_rating_created_idx',
        ),
    ]
