# Generated by Django 5.2.7 on 2025-11-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_product_barcode'),
        ('quiz', '0017_remove_quizfeedback_contact_email'),
    ]

    operations = [
    ]
