# Generated by Django 5.2.7 on 2025-11-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_merge_20251106_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='is_anonymous',
            field=models.BooleanField(default=False, help_text="When true, the review hides the reviewer's identity publicly."),
        ),
    ]
