# Generated by Django 5.2.6 on 2025-11-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_add_review_anonymous_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchpick',
            name='product_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
