# Generated by Django 5.2.6 on 2025-10-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_options_userprofile_avatar_url_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userprofile',
            name='uniq_contact_email_when_present',
        ),
        migrations.RemoveIndex(
            model_name='userprofile',
            name='core_userpr_contact_0ab1aa_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='display_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('prefer_not', 'Prefer not to say')], max_length=20, null=True),
        ),
    ]
