# Generated by Django 5.2.6 on 2025-10-02 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_userprofile_uniq_contact_email_when_present_and_more'),
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_concerns', models.JSONField(blank=True, default=list)),
                ('secondary_concerns', models.JSONField(blank=True, default=list)),
                ('eye_area_concerns', models.JSONField(blank=True, default=list)),
                ('skin_type', models.CharField(blank=True, choices=[('normal', 'Normal'), ('oily', 'Oily'), ('dry', 'Dry'), ('combination', 'Combination')], max_length=20)),
                ('sensitivity', models.CharField(blank=True, choices=[('yes', 'Yes'), ('sometimes', 'Sometimes'), ('no', 'No')], max_length=12)),
                ('pregnant_or_breastfeeding', models.BooleanField(blank=True, null=True)),
                ('ingredient_restrictions', models.JSONField(blank=True, default=list)),
                ('budget', models.CharField(blank=True, choices=[('affordable', 'Affordable'), ('mid', 'Mid-range'), ('premium', 'Premium / luxury')], max_length=12)),
                ('answer_snapshot', models.JSONField(blank=True, default=dict)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
                ('score_version', models.CharField(default='v1', max_length=20)),
                ('is_latest', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_profile', to='quiz.quizsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'created_at'], name='core_skinpr_user_id_c6b0ca_idx'), models.Index(fields=['user', 'is_latest'], name='core_skinpr_user_id_1558a9_idx')],
            },
        ),
    ]
