# Generated by Django 5.2.6 on 2025-10-23 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_skinfact_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='skinfacttopic',
            new_name='core_skinfa_section_0e2f61_idx',
            old_name='core_skinfac_section_409f40_idx',
        ),
        migrations.RenameIndex(
            model_name='skinfacttopic',
            new_name='core_skinfa_view_co_6b927a_idx',
            old_name='core_skinfac_view_co_d442c0_idx',
        ),
        migrations.RenameIndex(
            model_name='skinfactview',
            new_name='core_skinfa_user_id_73c988_idx',
            old_name='core_skinfac_user_vi_6d8154_idx',
        ),
        migrations.RenameIndex(
            model_name='skinfactview',
            new_name='core_skinfa_topic_i_13795a_idx',
            old_name='core_skinfac_topic_v_7c8b44_idx',
        ),
    ]
