# Generated by Django 5.2.6 on 2025-10-26 12:44

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_core_skinfac_section_409f40_idx_core_skinfa_section_0e2f61_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skinfacttopic',
            name='last_updated',
            field=models.DateField(default=django.utils.timezone.now, help_text='When this topic was last reviewed / fact-checked for accuracy.'),
        ),
        migrations.AlterField(
            model_name='skinfactcontentblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading / Section Title'), ('text', 'Text Section')], help_text="Use 'heading' for section headers, 'text' for normal explanatory content.", max_length=20),
        ),
        migrations.AlterField(
            model_name='skinfactcontentblock',
            name='heading',
            field=models.CharField(blank=True, help_text="Small heading/title for this block, e.g. 'How to Use Hyaluronic Acid Effectively'.", max_length=180),
        ),
        migrations.AlterField(
            model_name='skinfactcontentblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional. Example: serum texture, hydrated skin close-up.', null=True, upload_to='facts/blocks/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='skinfactcontentblock',
            name='image_alt',
            field=models.CharField(blank=True, help_text="Describe the image for accessibility. Example: 'Transparent serum drop with bubbles'.", max_length=160),
        ),
        migrations.AlterField(
            model_name='skinfactcontentblock',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order, starting from 0. Lower = appears earlier.'),
        ),
        migrations.AlterField(
            model_name='skinfactcontentblock',
            name='text',
            field=models.TextField(blank=True, help_text='Main body text (3–6 sentences).'),
        ),
    ]
