# Generated by Django 5.2.7 on 2025-10-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_skinfacttopic_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinfactcontentblock',
            name='block_type',
            field=models.CharField(choices=[('heading', 'Heading / Section Title'), ('text', 'Text Section'), ('paragraph', 'Paragraph'), ('image', 'Image + Text')], help_text="Use 'heading' for section headers, 'text' for normal explanatory content.", max_length=20),
        ),
    ]
