# Generated by Django 5.2.7 on 2025-11-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_newslettersubscriber'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='newslettersubscriber',
            new_name='core_newsle_subscri_8b135b_idx',
            old_name='core_newsle_subscri_1d53d1_idx',
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
