# Generated by Django 5.2.6 on 2025-01-XX XX:XX

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinfactcontentblock',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Optional. Example: serum texture, hydrated skin close-up. Supported formats: JPG, PNG, WebP, AVIF. WebP and AVIF provide better compression and quality.',
                null=True,
                upload_to='facts/blocks/',
                validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif'])]
            ),
        ),
        migrations.AlterField(
            model_name='skinfacttopic',
            name='hero_image',
            field=models.ImageField(
                blank=True,
                help_text='Supported formats: JPG, PNG, WebP, AVIF. WebP and AVIF provide better compression and quality.',
                upload_to='facts/hero/',
                validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif'])]
            ),
        ),
    ]

