# Generated by Django 5.2.6 on 2025-11-08 15:02

import django.core.validators
from django.db import migrations, models
from django.db import connection


def enforce_either_or_logic(apps, schema_editor):
    """
    Enforce either/or logic: blocks should have either content OR image, not both.
    If both exist, prioritize image (clear content).
    """
    # Use raw SQL to avoid ORM issues with model state
    with connection.cursor() as cursor:
        # Get all blocks with both content and image
        cursor.execute("""
            SELECT id 
            FROM core_skinfactcontentblock
            WHERE content IS NOT NULL 
            AND content != ''
            AND image IS NOT NULL
            AND image != ''
        """)
        
        for row in cursor.fetchall():
            block_id = row[0]
            # Clear content if image exists (prioritize image)
            cursor.execute("""
                UPDATE core_skinfactcontentblock
                SET content = ''
                WHERE id = %s
            """, [block_id])


def reverse_migrate_blocks(apps, schema_editor):
    """Reverse migration - no-op since we're just enforcing data rules"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_webp_avif_support_to_fact_images'),
    ]

    operations = [
        # Enforce either/or data logic
        migrations.RunPython(enforce_either_or_logic, reverse_migrate_blocks),
        # Update field definitions to match the model (state operations only)
        # These don't change the database, just update Django's migration state
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operations needed - schema is already correct
            ],
            state_operations=[
                # Add content field to migration state if it doesn't exist
                migrations.AddField(
                    model_name='skinfactcontentblock',
                    name='content',
                    field=models.TextField(blank=True, help_text='Markdown content for text blocks. Supports headings (# ## ###), lists, links, bold (**text**), italic (*text*). Leave empty if this is an image block.'),
                ),
                # Remove old fields from migration state
                migrations.RemoveField(
                    model_name='skinfactcontentblock',
                    name='block_type',
                ),
                migrations.RemoveField(
                    model_name='skinfactcontentblock',
                    name='heading',
                ),
                migrations.RemoveField(
                    model_name='skinfactcontentblock',
                    name='text',
                ),
                # Update field definitions
                migrations.AlterField(
                    model_name='skinfactcontentblock',
                    name='image',
                    field=models.ImageField(blank=True, help_text='Image for image blocks. Supported formats: JPG, PNG, WebP, AVIF. Leave empty if this is a text block.', null=True, upload_to='facts/blocks/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif'])]),
                ),
                migrations.AlterField(
                    model_name='skinfactcontentblock',
                    name='image_alt',
                    field=models.CharField(blank=True, help_text='Required if image is provided. Describe the image for accessibility.', max_length=160),
                ),
                migrations.AlterField(
                    model_name='skinfacttopic',
                    name='section',
                    field=models.CharField(choices=[('knowledge', 'Skin Knowledge'), ('trending', 'Trending Skincare'), ('fact_check', 'Fact Check'), ('ingredient_spotlight', 'Ingredient Spotlight')], max_length=20),
                ),
            ],
        ),
    ]
