# Generated by Django 5.2.7 on 2025-01-XX XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_webp_avif_support_to_fact_images'),
    ]

    operations = [
        # Database is already in the correct state - content exists, old fields removed
        # This migration only updates Django's migration state to match the database
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # No database operations - schema already matches the model
            ],
            state_operations=[
                # Remove old fields from migration state
                migrations.RemoveField(
                    model_name='skinfactcontentblock',
                    name='block_type',
                ),
                migrations.RemoveField(
                    model_name='skinfactcontentblock',
                    name='heading',
                ),
                migrations.RemoveField(
                    model_name='skinfactcontentblock',
                    name='text',
                ),
                # Add content field to migration state
                migrations.AddField(
                    model_name='skinfactcontentblock',
                    name='content',
                    field=models.TextField(
                        blank=True,
                        help_text='Markdown content for text blocks. Supports headings (# ## ###), lists, links, bold (**text**), italic (*text*). Leave empty if this is an image block.',
                    ),
                ),
            ],
        ),
    ]

