# Generated by Django 5.2.6 on 2025-11-15 10:22

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_apiclient'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_apic_key_pre_e879ba_idx" RENAME TO "core_apicli_key_pre_a1b527_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_apicli_key_pre_a1b527_idx" RENAME TO "core_apic_key_pre_e879ba_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='apiclient',
                    new_name='core_apicli_key_pre_a1b527_idx',
                    old_name='core_apic_key_pre_e879ba_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_apic_is_acti_499af3_idx" RENAME TO "core_apicli_is_acti_76842f_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_apicli_is_acti_76842f_idx" RENAME TO "core_apic_is_acti_499af3_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='apiclient',
                    new_name='core_apicli_is_acti_76842f_idx',
                    old_name='core_apic_is_acti_499af3_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_wish_user_created_idx" RENAME TO "core_wishli_user_id_e6a10a_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_wishli_user_id_e6a10a_idx" RENAME TO "core_wish_user_created_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='wishlistitem',
                    new_name='core_wishli_user_id_e6a10a_idx',
                    old_name='core_wish_user_created_idx',
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER INDEX IF EXISTS "core_wish_prod_created_idx" RENAME TO "core_wishli_product_232856_idx";',
                    reverse_sql='ALTER INDEX IF EXISTS "core_wishli_product_232856_idx" RENAME TO "core_wish_prod_created_idx";',
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name='wishlistitem',
                    new_name='core_wishli_product_232856_idx',
                    old_name='core_wish_prod_created_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='skinfactcontentblock',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for image blocks. Supported formats: JPG, PNG, WebP, AVIF. Leave empty if this is a text block.', null=True, upload_to='facts/blocks/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif']), core.validators.validate_image_mime_type, core.validators.validate_fact_image_size]),
        ),
        migrations.AlterField(
            model_name='skinfacttopic',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Supported formats: JPG, PNG, WebP, AVIF. WebP and AVIF provide better compression and quality.', upload_to='facts/hero/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'avif']), core.validators.validate_image_mime_type, core.validators.validate_fact_image_size]),
        ),
    ]
